// Generated by tools/generate_bindings.zig. Do not edit.
const generated = @import("generated_classes/index.zig");

pub const Vector = @import("abi.zig").Vector;
pub const Color = @import("abi.zig").Color;
pub const Transform2D = @import("abi.zig").Transform2D;
pub const Transform3D = @import("abi.zig").Transform3D;
pub const Rect2 = @import("abi.zig").Rect2;
pub const HorizontalAlignment = generated.HorizontalAlignment;
pub const Side = generated.Side;
pub const EulerOrder = generated.EulerOrder;

pub const Node = generated.Node;
pub const CanvasItem = generated.CanvasItem;
pub const Control = generated.Control;
pub const Node2D = generated.Node2D;
pub const Sprite2D = generated.Sprite2D;
pub const Node3D = generated.Node3D;
pub const Window = generated.Window;
pub const SceneTree = generated.SceneTree;
pub const Tween = generated.Tween;
pub const Viewport = generated.Viewport;
pub const MultiplayerAPI = generated.MultiplayerAPI;
pub const Texture2D = generated.Texture2D;
pub const StyleBox = generated.StyleBox;
pub const Font = generated.Font;
pub const TextServer = generated.TextServer;
pub const Mesh = generated.Mesh;
pub const MultiMesh = generated.MultiMesh;
pub const CanvasLayer = generated.CanvasLayer;
pub const World2D = generated.World2D;
pub const Material = generated.Material;
pub const InputEvent = generated.InputEvent;
pub const Theme = generated.Theme;
pub const AccessibilityServer = generated.AccessibilityServer;
pub const World3D = generated.World3D;
pub const Node3DGizmo = generated.Node3DGizmo;
