// Generated by tools/generate_bindings.py. Do not edit.
// Godot 4.7.0 stable; precision: single.
const abi = @import("abi.zig");
const support = @import("class_support.zig");

pub const Vector2 = abi.Vector2;

pub const Side = enum(i64) {
    side_left = 0,
    side_top = 1,
    side_right = 2,
    side_bottom = 3,
};

pub const EulerOrder = enum(i64) {
    euler_order_xyz = 0,
    euler_order_xzy = 1,
    euler_order_yxz = 2,
    euler_order_yzx = 3,
    euler_order_zxy = 4,
    euler_order_zyx = 5,
};

pub const Node = extern struct {
    owner: u64,

    pub const godot_class = "Node";
    pub const emitSignal = support.emitSignal;

    pub const InternalMode = enum(i64) {
        internal_mode_disabled = 0,
        internal_mode_front = 1,
        internal_mode_back = 2,
    };

    pub const ProcessMode = enum(i64) {
        process_mode_inherit = 0,
        process_mode_pausable = 1,
        process_mode_when_paused = 2,
        process_mode_always = 3,
        process_mode_disabled = 4,
    };

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }
};

pub const CanvasItem = extern struct {
    owner: u64,

    pub const godot_class = "CanvasItem";
    pub const emitSignal = support.emitSignal;

    pub const TextureFilter = enum(i64) {
        texture_filter_parent_node = 0,
        texture_filter_nearest = 1,
        texture_filter_linear = 2,
        texture_filter_nearest_with_mipmaps = 3,
        texture_filter_linear_with_mipmaps = 4,
        texture_filter_nearest_with_mipmaps_anisotropic = 5,
        texture_filter_linear_with_mipmaps_anisotropic = 6,
        texture_filter_max = 7,
    };

    pub const TextureRepeat = enum(i64) {
        texture_repeat_parent_node = 0,
        texture_repeat_disabled = 1,
        texture_repeat_enabled = 2,
        texture_repeat_mirror = 3,
        texture_repeat_max = 4,
    };

    pub const ClipChildrenMode = enum(i64) {
        clip_children_disabled = 0,
        clip_children_only = 1,
        clip_children_and_draw = 2,
        clip_children_max = 3,
    };

    pub const OversamplingWithScale = enum(i64) {
        oversampling_with_scale_parent_node = 0,
        oversampling_with_scale_disabled = 1,
        oversampling_with_scale_enabled = 2,
        oversampling_with_scale_max = 3,
    };

    pub fn asNode(self: @This()) Node {
        return .{ .owner = self.owner };
    }

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }

    pub fn setVisible(self: @This(), visible: bool) !void {
        try support.callVoid(self, "set_visible", .{visible});
    }

    pub fn isVisible(self: @This()) !bool {
        return support.call(self, bool, "is_visible", .{});
    }

    pub fn isVisibleInTree(self: @This()) !bool {
        return support.call(self, bool, "is_visible_in_tree", .{});
    }

    pub fn show(self: @This()) !void {
        try support.callVoid(self, "show", .{});
    }

    pub fn hide(self: @This()) !void {
        try support.callVoid(self, "hide", .{});
    }

    pub fn queueRedraw(self: @This()) !void {
        try support.callVoid(self, "queue_redraw", .{});
    }

    pub fn moveToFront(self: @This()) !void {
        try support.callVoid(self, "move_to_front", .{});
    }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_as_top_level", .{enable});
    }

    pub fn isSetAsTopLevel(self: @This()) !bool {
        return support.call(self, bool, "is_set_as_top_level", .{});
    }

    pub fn setLightMask(self: @This(), light_mask: i64) !void {
        try support.callVoid(self, "set_light_mask", .{light_mask});
    }

    pub fn getLightMask(self: @This()) !i64 {
        return support.call(self, i64, "get_light_mask", .{});
    }

    pub fn setZIndex(self: @This(), z_index: i64) !void {
        try support.callVoid(self, "set_z_index", .{z_index});
    }

    pub fn getZIndex(self: @This()) !i64 {
        return support.call(self, i64, "get_z_index", .{});
    }

    pub fn setZAsRelative(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_z_as_relative", .{enable});
    }

    pub fn isZRelative(self: @This()) !bool {
        return support.call(self, bool, "is_z_relative", .{});
    }

    pub fn setYSortEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_y_sort_enabled", .{enabled});
    }

    pub fn isYSortEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_y_sort_enabled", .{});
    }

    pub fn setDrawBehindParent(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_draw_behind_parent", .{enable});
    }

    pub fn isDrawBehindParentEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_draw_behind_parent_enabled", .{});
    }

    pub fn drawSetTransform(self: @This(), position: abi.Vector2, rotation: f64, scale: abi.Vector2) !void {
        try support.callVoid(self, "draw_set_transform", .{ position, rotation, scale });
    }

    pub fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void {
        try support.callVoid(self, "draw_animation_slice", .{ animation_length, slice_begin, slice_end, offset });
    }

    pub fn drawEndAnimation(self: @This()) !void {
        try support.callVoid(self, "draw_end_animation", .{});
    }

    pub fn getLocalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_local_mouse_position", .{});
    }

    pub fn getGlobalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_mouse_position", .{});
    }

    pub fn setUseParentMaterial(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_use_parent_material", .{enable});
    }

    pub fn getUseParentMaterial(self: @This()) !bool {
        return support.call(self, bool, "get_use_parent_material", .{});
    }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_local_transform", .{enable});
    }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_local_transform_notification_enabled", .{});
    }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_transform", .{enable});
    }

    pub fn isTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_transform_notification_enabled", .{});
    }

    pub fn forceUpdateTransform(self: @This()) !void {
        try support.callVoid(self, "force_update_transform", .{});
    }

    pub fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "make_canvas_position_local", .{viewport_point});
    }

    pub fn setVisibilityLayer(self: @This(), layer: i64) !void {
        try support.callVoid(self, "set_visibility_layer", .{layer});
    }

    pub fn getVisibilityLayer(self: @This()) !i64 {
        return support.call(self, i64, "get_visibility_layer", .{});
    }

    pub fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void {
        try support.callVoid(self, "set_visibility_layer_bit", .{ layer, enabled });
    }

    pub fn getVisibilityLayerBit(self: @This(), layer: i64) !bool {
        return support.call(self, bool, "get_visibility_layer_bit", .{layer});
    }

    pub fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void {
        try support.callVoid(self, "set_texture_filter", .{mode});
    }

    pub fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter {
        return support.call(self, CanvasItem.TextureFilter, "get_texture_filter", .{});
    }

    pub fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void {
        try support.callVoid(self, "set_texture_repeat", .{mode});
    }

    pub fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat {
        return support.call(self, CanvasItem.TextureRepeat, "get_texture_repeat", .{});
    }

    pub fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void {
        try support.callVoid(self, "set_clip_children_mode", .{mode});
    }

    pub fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode {
        return support.call(self, CanvasItem.ClipChildrenMode, "get_clip_children_mode", .{});
    }

    pub fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void {
        try support.callVoid(self, "set_oversampling_with_scale", .{enabled});
    }

    pub fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale {
        return support.call(self, CanvasItem.OversamplingWithScale, "get_oversampling_with_scale", .{});
    }
};

pub const Control = extern struct {
    owner: u64,

    pub const godot_class = "Control";
    pub const emitSignal = support.emitSignal;

    pub const LayoutPreset = enum(i64) {
        preset_top_left = 0,
        preset_top_right = 1,
        preset_bottom_left = 2,
        preset_bottom_right = 3,
        preset_center_left = 4,
        preset_center_top = 5,
        preset_center_right = 6,
        preset_center_bottom = 7,
        preset_center = 8,
        preset_left_wide = 9,
        preset_top_wide = 10,
        preset_right_wide = 11,
        preset_bottom_wide = 12,
        preset_vcenter_wide = 13,
        preset_hcenter_wide = 14,
        preset_full_rect = 15,
    };

    pub const LayoutPresetMode = enum(i64) {
        preset_mode_minsize = 0,
        preset_mode_keep_width = 1,
        preset_mode_keep_height = 2,
        preset_mode_keep_size = 3,
    };

    pub const FocusMode = enum(i64) {
        focus_none = 0,
        focus_click = 1,
        focus_all = 2,
        focus_accessibility = 3,
    };

    pub const SizeFlags = enum(i64) {
        size_shrink_begin = 0,
        size_fill = 1,
        size_expand = 2,
        size_expand_fill = 3,
        size_shrink_center = 4,
        size_shrink_end = 8,
        _,
    };

    pub const MouseFilter = enum(i64) {
        mouse_filter_stop = 0,
        mouse_filter_pass = 1,
        mouse_filter_ignore = 2,
    };

    pub const LayoutDirection = enum(i64) {
        layout_direction_inherited = 0,
        layout_direction_application_locale = 1,
        layout_direction_ltr = 2,
        layout_direction_rtl = 3,
        layout_direction_system_locale = 4,
        layout_direction_max = 5,
        pub const layout_direction_locale: @This() = .layout_direction_application_locale;
    };

    pub fn asNode(self: @This()) Node {
        return .{ .owner = self.owner };
    }

    pub fn asCanvasItem(self: @This()) CanvasItem {
        return .{ .owner = self.owner };
    }

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }

    pub fn setVisible(self: @This(), visible: bool) !void {
        try support.callVoid(self, "set_visible", .{visible});
    }

    pub fn isVisible(self: @This()) !bool {
        return support.call(self, bool, "is_visible", .{});
    }

    pub fn isVisibleInTree(self: @This()) !bool {
        return support.call(self, bool, "is_visible_in_tree", .{});
    }

    pub fn show(self: @This()) !void {
        try support.callVoid(self, "show", .{});
    }

    pub fn hide(self: @This()) !void {
        try support.callVoid(self, "hide", .{});
    }

    pub fn queueRedraw(self: @This()) !void {
        try support.callVoid(self, "queue_redraw", .{});
    }

    pub fn moveToFront(self: @This()) !void {
        try support.callVoid(self, "move_to_front", .{});
    }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_as_top_level", .{enable});
    }

    pub fn isSetAsTopLevel(self: @This()) !bool {
        return support.call(self, bool, "is_set_as_top_level", .{});
    }

    pub fn setLightMask(self: @This(), light_mask: i64) !void {
        try support.callVoid(self, "set_light_mask", .{light_mask});
    }

    pub fn getLightMask(self: @This()) !i64 {
        return support.call(self, i64, "get_light_mask", .{});
    }

    pub fn setZIndex(self: @This(), z_index: i64) !void {
        try support.callVoid(self, "set_z_index", .{z_index});
    }

    pub fn getZIndex(self: @This()) !i64 {
        return support.call(self, i64, "get_z_index", .{});
    }

    pub fn setZAsRelative(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_z_as_relative", .{enable});
    }

    pub fn isZRelative(self: @This()) !bool {
        return support.call(self, bool, "is_z_relative", .{});
    }

    pub fn setYSortEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_y_sort_enabled", .{enabled});
    }

    pub fn isYSortEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_y_sort_enabled", .{});
    }

    pub fn setDrawBehindParent(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_draw_behind_parent", .{enable});
    }

    pub fn isDrawBehindParentEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_draw_behind_parent_enabled", .{});
    }

    pub fn drawSetTransform(self: @This(), position: abi.Vector2, rotation: f64, scale: abi.Vector2) !void {
        try support.callVoid(self, "draw_set_transform", .{ position, rotation, scale });
    }

    pub fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void {
        try support.callVoid(self, "draw_animation_slice", .{ animation_length, slice_begin, slice_end, offset });
    }

    pub fn drawEndAnimation(self: @This()) !void {
        try support.callVoid(self, "draw_end_animation", .{});
    }

    pub fn getLocalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_local_mouse_position", .{});
    }

    pub fn getGlobalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_mouse_position", .{});
    }

    pub fn setUseParentMaterial(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_use_parent_material", .{enable});
    }

    pub fn getUseParentMaterial(self: @This()) !bool {
        return support.call(self, bool, "get_use_parent_material", .{});
    }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_local_transform", .{enable});
    }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_local_transform_notification_enabled", .{});
    }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_transform", .{enable});
    }

    pub fn isTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_transform_notification_enabled", .{});
    }

    pub fn forceUpdateTransform(self: @This()) !void {
        try support.callVoid(self, "force_update_transform", .{});
    }

    pub fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "make_canvas_position_local", .{viewport_point});
    }

    pub fn setVisibilityLayer(self: @This(), layer: i64) !void {
        try support.callVoid(self, "set_visibility_layer", .{layer});
    }

    pub fn getVisibilityLayer(self: @This()) !i64 {
        return support.call(self, i64, "get_visibility_layer", .{});
    }

    pub fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void {
        try support.callVoid(self, "set_visibility_layer_bit", .{ layer, enabled });
    }

    pub fn getVisibilityLayerBit(self: @This(), layer: i64) !bool {
        return support.call(self, bool, "get_visibility_layer_bit", .{layer});
    }

    pub fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void {
        try support.callVoid(self, "set_texture_filter", .{mode});
    }

    pub fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter {
        return support.call(self, CanvasItem.TextureFilter, "get_texture_filter", .{});
    }

    pub fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void {
        try support.callVoid(self, "set_texture_repeat", .{mode});
    }

    pub fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat {
        return support.call(self, CanvasItem.TextureRepeat, "get_texture_repeat", .{});
    }

    pub fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void {
        try support.callVoid(self, "set_clip_children_mode", .{mode});
    }

    pub fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode {
        return support.call(self, CanvasItem.ClipChildrenMode, "get_clip_children_mode", .{});
    }

    pub fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void {
        try support.callVoid(self, "set_oversampling_with_scale", .{enabled});
    }

    pub fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale {
        return support.call(self, CanvasItem.OversamplingWithScale, "get_oversampling_with_scale", .{});
    }

    pub fn acceptEvent(self: @This()) !void {
        try support.callVoid(self, "accept_event", .{});
    }

    pub fn getMaximumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_maximum_size", .{});
    }

    pub fn getCombinedMaximumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_combined_maximum_size", .{});
    }

    pub fn getMinimumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_minimum_size", .{});
    }

    pub fn getCombinedMinimumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_combined_minimum_size", .{});
    }

    pub fn getBoundMinimumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_bound_minimum_size", .{});
    }

    pub fn setAnchorsPreset(self: @This(), preset: Control.LayoutPreset, keep_offsets: bool) !void {
        try support.callVoid(self, "set_anchors_preset", .{ preset, keep_offsets });
    }

    pub fn setOffsetsPreset(self: @This(), preset: Control.LayoutPreset, resize_mode: Control.LayoutPresetMode, margin: i64) !void {
        try support.callVoid(self, "set_offsets_preset", .{ preset, resize_mode, margin });
    }

    pub fn setAnchorsAndOffsetsPreset(self: @This(), preset: Control.LayoutPreset, resize_mode: Control.LayoutPresetMode, margin: i64) !void {
        try support.callVoid(self, "set_anchors_and_offsets_preset", .{ preset, resize_mode, margin });
    }

    pub fn setAnchor(self: @This(), side: Side, anchor: f64, keep_offset: bool, push_opposite_anchor: bool) !void {
        try support.callVoid(self, "set_anchor", .{ side, anchor, keep_offset, push_opposite_anchor });
    }

    pub fn getAnchor(self: @This(), side: Side) !f64 {
        return support.call(self, f64, "get_anchor", .{side});
    }

    pub fn setOffset(self: @This(), side: Side, offset: f64) !void {
        try support.callVoid(self, "set_offset", .{ side, offset });
    }

    pub fn getOffset(self: @This(), offset: Side) !f64 {
        return support.call(self, f64, "get_offset", .{offset});
    }

    pub fn setAnchorAndOffset(self: @This(), side: Side, anchor: f64, offset: f64, push_opposite_anchor: bool) !void {
        try support.callVoid(self, "set_anchor_and_offset", .{ side, anchor, offset, push_opposite_anchor });
    }

    pub fn setBegin(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_begin", .{position});
    }

    pub fn setEnd(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_end", .{position});
    }

    pub fn setPosition(self: @This(), position: abi.Vector2, keep_offsets: bool) !void {
        try support.callVoid(self, "set_position", .{ position, keep_offsets });
    }

    pub fn setSize(self: @This(), size: abi.Vector2, keep_offsets: bool) !void {
        try support.callVoid(self, "set_size", .{ size, keep_offsets });
    }

    pub fn resetSize(self: @This()) !void {
        try support.callVoid(self, "reset_size", .{});
    }

    pub fn setCustomMaximumSize(self: @This(), size: abi.Vector2) !void {
        try support.callVoid(self, "set_custom_maximum_size", .{size});
    }

    pub fn setCustomMinimumSize(self: @This(), size: abi.Vector2) !void {
        try support.callVoid(self, "set_custom_minimum_size", .{size});
    }

    pub fn setGlobalPosition(self: @This(), position: abi.Vector2, keep_offsets: bool) !void {
        try support.callVoid(self, "set_global_position", .{ position, keep_offsets });
    }

    pub fn setRotation(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_rotation", .{radians});
    }

    pub fn setRotationDegrees(self: @This(), degrees: f64) !void {
        try support.callVoid(self, "set_rotation_degrees", .{degrees});
    }

    pub fn setScale(self: @This(), scale: abi.Vector2) !void {
        try support.callVoid(self, "set_scale", .{scale});
    }

    pub fn setPivotOffset(self: @This(), pivot_offset: abi.Vector2) !void {
        try support.callVoid(self, "set_pivot_offset", .{pivot_offset});
    }

    pub fn setPivotOffsetRatio(self: @This(), ratio: abi.Vector2) !void {
        try support.callVoid(self, "set_pivot_offset_ratio", .{ratio});
    }

    pub fn getBegin(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_begin", .{});
    }

    pub fn getEnd(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_end", .{});
    }

    pub fn getPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_position", .{});
    }

    pub fn getSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_size", .{});
    }

    pub fn getRotation(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation", .{});
    }

    pub fn getRotationDegrees(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation_degrees", .{});
    }

    pub fn getScale(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_scale", .{});
    }

    pub fn getPivotOffset(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_pivot_offset", .{});
    }

    pub fn getPivotOffsetRatio(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_pivot_offset_ratio", .{});
    }

    pub fn getCombinedPivotOffset(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_combined_pivot_offset", .{});
    }

    pub fn getCustomMaximumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_custom_maximum_size", .{});
    }

    pub fn getCustomMinimumSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_custom_minimum_size", .{});
    }

    pub fn getParentAreaSize(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_parent_area_size", .{});
    }

    pub fn getGlobalPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_position", .{});
    }

    pub fn getScreenPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_screen_position", .{});
    }

    pub fn setFocusMode(self: @This(), mode: Control.FocusMode) !void {
        try support.callVoid(self, "set_focus_mode", .{mode});
    }

    pub fn getFocusMode(self: @This()) !Control.FocusMode {
        return support.call(self, Control.FocusMode, "get_focus_mode", .{});
    }

    pub fn getFocusModeWithOverride(self: @This()) !Control.FocusMode {
        return support.call(self, Control.FocusMode, "get_focus_mode_with_override", .{});
    }

    pub fn hasFocus(self: @This(), ignore_hidden_focus: bool) !bool {
        return support.call(self, bool, "has_focus", .{ignore_hidden_focus});
    }

    pub fn grabFocus(self: @This(), hide_focus: bool) !void {
        try support.callVoid(self, "grab_focus", .{hide_focus});
    }

    pub fn releaseFocus(self: @This()) !void {
        try support.callVoid(self, "release_focus", .{});
    }

    pub fn findPrevValidFocus(self: @This()) !?Control {
        return support.call(self, ?Control, "find_prev_valid_focus", .{});
    }

    pub fn findNextValidFocus(self: @This()) !?Control {
        return support.call(self, ?Control, "find_next_valid_focus", .{});
    }

    pub fn findValidFocusNeighbor(self: @This(), side: Side) !?Control {
        return support.call(self, ?Control, "find_valid_focus_neighbor", .{side});
    }

    pub fn setHSizeFlags(self: @This(), flags: Control.SizeFlags) !void {
        try support.callVoid(self, "set_h_size_flags", .{flags});
    }

    pub fn getHSizeFlags(self: @This()) !Control.SizeFlags {
        return support.call(self, Control.SizeFlags, "get_h_size_flags", .{});
    }

    pub fn setStretchRatio(self: @This(), ratio: f64) !void {
        try support.callVoid(self, "set_stretch_ratio", .{ratio});
    }

    pub fn getStretchRatio(self: @This()) !f64 {
        return support.call(self, f64, "get_stretch_ratio", .{});
    }

    pub fn setVSizeFlags(self: @This(), flags: Control.SizeFlags) !void {
        try support.callVoid(self, "set_v_size_flags", .{flags});
    }

    pub fn getVSizeFlags(self: @This()) !Control.SizeFlags {
        return support.call(self, Control.SizeFlags, "get_v_size_flags", .{});
    }

    pub fn getParentControl(self: @This()) !?Control {
        return support.call(self, ?Control, "get_parent_control", .{});
    }

    pub fn setMouseFilter(self: @This(), filter: Control.MouseFilter) !void {
        try support.callVoid(self, "set_mouse_filter", .{filter});
    }

    pub fn getMouseFilter(self: @This()) !Control.MouseFilter {
        return support.call(self, Control.MouseFilter, "get_mouse_filter", .{});
    }

    pub fn getMouseFilterWithOverride(self: @This()) !Control.MouseFilter {
        return support.call(self, Control.MouseFilter, "get_mouse_filter_with_override", .{});
    }

    pub fn setForcePassScrollEvents(self: @This(), force_pass_scroll_events: bool) !void {
        try support.callVoid(self, "set_force_pass_scroll_events", .{force_pass_scroll_events});
    }

    pub fn isForcePassScrollEvents(self: @This()) !bool {
        return support.call(self, bool, "is_force_pass_scroll_events", .{});
    }

    pub fn setClipContents(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_clip_contents", .{enable});
    }

    pub fn isClippingContents(self: @This()) !bool {
        return support.call(self, bool, "is_clipping_contents", .{});
    }

    pub fn grabClickFocus(self: @This()) !void {
        try support.callVoid(self, "grab_click_focus", .{});
    }

    pub fn setDragPreview(self: @This(), control: ?Control) !void {
        try support.callVoid(self, "set_drag_preview", .{control});
    }

    pub fn isDragSuccessful(self: @This()) !bool {
        return support.call(self, bool, "is_drag_successful", .{});
    }

    pub fn warpMouse(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "warp_mouse", .{position});
    }

    pub fn updateMaximumSize(self: @This()) !void {
        try support.callVoid(self, "update_maximum_size", .{});
    }

    pub fn updateMinimumSize(self: @This()) !void {
        try support.callVoid(self, "update_minimum_size", .{});
    }

    pub fn setLayoutDirection(self: @This(), direction: Control.LayoutDirection) !void {
        try support.callVoid(self, "set_layout_direction", .{direction});
    }

    pub fn getLayoutDirection(self: @This()) !Control.LayoutDirection {
        return support.call(self, Control.LayoutDirection, "get_layout_direction", .{});
    }

    pub fn isLayoutRtl(self: @This()) !bool {
        return support.call(self, bool, "is_layout_rtl", .{});
    }
};

pub const Node2D = extern struct {
    owner: u64,

    pub const godot_class = "Node2D";
    pub const emitSignal = support.emitSignal;

    pub fn asNode(self: @This()) Node {
        return .{ .owner = self.owner };
    }

    pub fn asCanvasItem(self: @This()) CanvasItem {
        return .{ .owner = self.owner };
    }

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }

    pub fn setVisible(self: @This(), visible: bool) !void {
        try support.callVoid(self, "set_visible", .{visible});
    }

    pub fn isVisible(self: @This()) !bool {
        return support.call(self, bool, "is_visible", .{});
    }

    pub fn isVisibleInTree(self: @This()) !bool {
        return support.call(self, bool, "is_visible_in_tree", .{});
    }

    pub fn show(self: @This()) !void {
        try support.callVoid(self, "show", .{});
    }

    pub fn hide(self: @This()) !void {
        try support.callVoid(self, "hide", .{});
    }

    pub fn queueRedraw(self: @This()) !void {
        try support.callVoid(self, "queue_redraw", .{});
    }

    pub fn moveToFront(self: @This()) !void {
        try support.callVoid(self, "move_to_front", .{});
    }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_as_top_level", .{enable});
    }

    pub fn isSetAsTopLevel(self: @This()) !bool {
        return support.call(self, bool, "is_set_as_top_level", .{});
    }

    pub fn setLightMask(self: @This(), light_mask: i64) !void {
        try support.callVoid(self, "set_light_mask", .{light_mask});
    }

    pub fn getLightMask(self: @This()) !i64 {
        return support.call(self, i64, "get_light_mask", .{});
    }

    pub fn setZIndex(self: @This(), z_index: i64) !void {
        try support.callVoid(self, "set_z_index", .{z_index});
    }

    pub fn getZIndex(self: @This()) !i64 {
        return support.call(self, i64, "get_z_index", .{});
    }

    pub fn setZAsRelative(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_z_as_relative", .{enable});
    }

    pub fn isZRelative(self: @This()) !bool {
        return support.call(self, bool, "is_z_relative", .{});
    }

    pub fn setYSortEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_y_sort_enabled", .{enabled});
    }

    pub fn isYSortEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_y_sort_enabled", .{});
    }

    pub fn setDrawBehindParent(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_draw_behind_parent", .{enable});
    }

    pub fn isDrawBehindParentEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_draw_behind_parent_enabled", .{});
    }

    pub fn drawSetTransform(self: @This(), position: abi.Vector2, rotation: f64, scale: abi.Vector2) !void {
        try support.callVoid(self, "draw_set_transform", .{ position, rotation, scale });
    }

    pub fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void {
        try support.callVoid(self, "draw_animation_slice", .{ animation_length, slice_begin, slice_end, offset });
    }

    pub fn drawEndAnimation(self: @This()) !void {
        try support.callVoid(self, "draw_end_animation", .{});
    }

    pub fn getLocalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_local_mouse_position", .{});
    }

    pub fn getGlobalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_mouse_position", .{});
    }

    pub fn setUseParentMaterial(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_use_parent_material", .{enable});
    }

    pub fn getUseParentMaterial(self: @This()) !bool {
        return support.call(self, bool, "get_use_parent_material", .{});
    }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_local_transform", .{enable});
    }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_local_transform_notification_enabled", .{});
    }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_transform", .{enable});
    }

    pub fn isTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_transform_notification_enabled", .{});
    }

    pub fn forceUpdateTransform(self: @This()) !void {
        try support.callVoid(self, "force_update_transform", .{});
    }

    pub fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "make_canvas_position_local", .{viewport_point});
    }

    pub fn setVisibilityLayer(self: @This(), layer: i64) !void {
        try support.callVoid(self, "set_visibility_layer", .{layer});
    }

    pub fn getVisibilityLayer(self: @This()) !i64 {
        return support.call(self, i64, "get_visibility_layer", .{});
    }

    pub fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void {
        try support.callVoid(self, "set_visibility_layer_bit", .{ layer, enabled });
    }

    pub fn getVisibilityLayerBit(self: @This(), layer: i64) !bool {
        return support.call(self, bool, "get_visibility_layer_bit", .{layer});
    }

    pub fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void {
        try support.callVoid(self, "set_texture_filter", .{mode});
    }

    pub fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter {
        return support.call(self, CanvasItem.TextureFilter, "get_texture_filter", .{});
    }

    pub fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void {
        try support.callVoid(self, "set_texture_repeat", .{mode});
    }

    pub fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat {
        return support.call(self, CanvasItem.TextureRepeat, "get_texture_repeat", .{});
    }

    pub fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void {
        try support.callVoid(self, "set_clip_children_mode", .{mode});
    }

    pub fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode {
        return support.call(self, CanvasItem.ClipChildrenMode, "get_clip_children_mode", .{});
    }

    pub fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void {
        try support.callVoid(self, "set_oversampling_with_scale", .{enabled});
    }

    pub fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale {
        return support.call(self, CanvasItem.OversamplingWithScale, "get_oversampling_with_scale", .{});
    }

    pub fn setPosition(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_position", .{position});
    }

    pub fn setRotation(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_rotation", .{radians});
    }

    pub fn setRotationDegrees(self: @This(), degrees: f64) !void {
        try support.callVoid(self, "set_rotation_degrees", .{degrees});
    }

    pub fn setSkew(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_skew", .{radians});
    }

    pub fn setScale(self: @This(), scale: abi.Vector2) !void {
        try support.callVoid(self, "set_scale", .{scale});
    }

    pub fn getPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_position", .{});
    }

    pub fn getRotation(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation", .{});
    }

    pub fn getRotationDegrees(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation_degrees", .{});
    }

    pub fn getSkew(self: @This()) !f64 {
        return support.call(self, f64, "get_skew", .{});
    }

    pub fn getScale(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_scale", .{});
    }

    pub fn rotate(self: @This(), radians: f64) !void {
        try support.callVoid(self, "rotate", .{radians});
    }

    pub fn moveLocalX(self: @This(), delta: f64, scaled: bool) !void {
        try support.callVoid(self, "move_local_x", .{ delta, scaled });
    }

    pub fn moveLocalY(self: @This(), delta: f64, scaled: bool) !void {
        try support.callVoid(self, "move_local_y", .{ delta, scaled });
    }

    pub fn translate(self: @This(), offset: abi.Vector2) !void {
        try support.callVoid(self, "translate", .{offset});
    }

    pub fn globalTranslate(self: @This(), offset: abi.Vector2) !void {
        try support.callVoid(self, "global_translate", .{offset});
    }

    pub fn applyScale(self: @This(), ratio: abi.Vector2) !void {
        try support.callVoid(self, "apply_scale", .{ratio});
    }

    pub fn setGlobalPosition(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_global_position", .{position});
    }

    pub fn getGlobalPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_position", .{});
    }

    pub fn setGlobalRotation(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_global_rotation", .{radians});
    }

    pub fn setGlobalRotationDegrees(self: @This(), degrees: f64) !void {
        try support.callVoid(self, "set_global_rotation_degrees", .{degrees});
    }

    pub fn getGlobalRotation(self: @This()) !f64 {
        return support.call(self, f64, "get_global_rotation", .{});
    }

    pub fn getGlobalRotationDegrees(self: @This()) !f64 {
        return support.call(self, f64, "get_global_rotation_degrees", .{});
    }

    pub fn setGlobalSkew(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_global_skew", .{radians});
    }

    pub fn getGlobalSkew(self: @This()) !f64 {
        return support.call(self, f64, "get_global_skew", .{});
    }

    pub fn setGlobalScale(self: @This(), scale: abi.Vector2) !void {
        try support.callVoid(self, "set_global_scale", .{scale});
    }

    pub fn getGlobalScale(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_scale", .{});
    }

    pub fn lookAt(self: @This(), point: abi.Vector2) !void {
        try support.callVoid(self, "look_at", .{point});
    }

    pub fn getAngleTo(self: @This(), point: abi.Vector2) !f64 {
        return support.call(self, f64, "get_angle_to", .{point});
    }

    pub fn toLocal(self: @This(), global_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "to_local", .{global_point});
    }

    pub fn toGlobal(self: @This(), local_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "to_global", .{local_point});
    }
};

pub const Sprite2D = extern struct {
    owner: u64,

    pub const godot_class = "Sprite2D";
    pub const emitSignal = support.emitSignal;

    pub fn asNode(self: @This()) Node {
        return .{ .owner = self.owner };
    }

    pub fn asCanvasItem(self: @This()) CanvasItem {
        return .{ .owner = self.owner };
    }

    pub fn asNode2D(self: @This()) Node2D {
        return .{ .owner = self.owner };
    }

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }

    pub fn setVisible(self: @This(), visible: bool) !void {
        try support.callVoid(self, "set_visible", .{visible});
    }

    pub fn isVisible(self: @This()) !bool {
        return support.call(self, bool, "is_visible", .{});
    }

    pub fn isVisibleInTree(self: @This()) !bool {
        return support.call(self, bool, "is_visible_in_tree", .{});
    }

    pub fn show(self: @This()) !void {
        try support.callVoid(self, "show", .{});
    }

    pub fn hide(self: @This()) !void {
        try support.callVoid(self, "hide", .{});
    }

    pub fn queueRedraw(self: @This()) !void {
        try support.callVoid(self, "queue_redraw", .{});
    }

    pub fn moveToFront(self: @This()) !void {
        try support.callVoid(self, "move_to_front", .{});
    }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_as_top_level", .{enable});
    }

    pub fn isSetAsTopLevel(self: @This()) !bool {
        return support.call(self, bool, "is_set_as_top_level", .{});
    }

    pub fn setLightMask(self: @This(), light_mask: i64) !void {
        try support.callVoid(self, "set_light_mask", .{light_mask});
    }

    pub fn getLightMask(self: @This()) !i64 {
        return support.call(self, i64, "get_light_mask", .{});
    }

    pub fn setZIndex(self: @This(), z_index: i64) !void {
        try support.callVoid(self, "set_z_index", .{z_index});
    }

    pub fn getZIndex(self: @This()) !i64 {
        return support.call(self, i64, "get_z_index", .{});
    }

    pub fn setZAsRelative(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_z_as_relative", .{enable});
    }

    pub fn isZRelative(self: @This()) !bool {
        return support.call(self, bool, "is_z_relative", .{});
    }

    pub fn setYSortEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_y_sort_enabled", .{enabled});
    }

    pub fn isYSortEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_y_sort_enabled", .{});
    }

    pub fn setDrawBehindParent(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_draw_behind_parent", .{enable});
    }

    pub fn isDrawBehindParentEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_draw_behind_parent_enabled", .{});
    }

    pub fn drawSetTransform(self: @This(), position: abi.Vector2, rotation: f64, scale: abi.Vector2) !void {
        try support.callVoid(self, "draw_set_transform", .{ position, rotation, scale });
    }

    pub fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void {
        try support.callVoid(self, "draw_animation_slice", .{ animation_length, slice_begin, slice_end, offset });
    }

    pub fn drawEndAnimation(self: @This()) !void {
        try support.callVoid(self, "draw_end_animation", .{});
    }

    pub fn getLocalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_local_mouse_position", .{});
    }

    pub fn getGlobalMousePosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_mouse_position", .{});
    }

    pub fn setUseParentMaterial(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_use_parent_material", .{enable});
    }

    pub fn getUseParentMaterial(self: @This()) !bool {
        return support.call(self, bool, "get_use_parent_material", .{});
    }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_local_transform", .{enable});
    }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_local_transform_notification_enabled", .{});
    }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_transform", .{enable});
    }

    pub fn isTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_transform_notification_enabled", .{});
    }

    pub fn forceUpdateTransform(self: @This()) !void {
        try support.callVoid(self, "force_update_transform", .{});
    }

    pub fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "make_canvas_position_local", .{viewport_point});
    }

    pub fn setVisibilityLayer(self: @This(), layer: i64) !void {
        try support.callVoid(self, "set_visibility_layer", .{layer});
    }

    pub fn getVisibilityLayer(self: @This()) !i64 {
        return support.call(self, i64, "get_visibility_layer", .{});
    }

    pub fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void {
        try support.callVoid(self, "set_visibility_layer_bit", .{ layer, enabled });
    }

    pub fn getVisibilityLayerBit(self: @This(), layer: i64) !bool {
        return support.call(self, bool, "get_visibility_layer_bit", .{layer});
    }

    pub fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void {
        try support.callVoid(self, "set_texture_filter", .{mode});
    }

    pub fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter {
        return support.call(self, CanvasItem.TextureFilter, "get_texture_filter", .{});
    }

    pub fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void {
        try support.callVoid(self, "set_texture_repeat", .{mode});
    }

    pub fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat {
        return support.call(self, CanvasItem.TextureRepeat, "get_texture_repeat", .{});
    }

    pub fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void {
        try support.callVoid(self, "set_clip_children_mode", .{mode});
    }

    pub fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode {
        return support.call(self, CanvasItem.ClipChildrenMode, "get_clip_children_mode", .{});
    }

    pub fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void {
        try support.callVoid(self, "set_oversampling_with_scale", .{enabled});
    }

    pub fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale {
        return support.call(self, CanvasItem.OversamplingWithScale, "get_oversampling_with_scale", .{});
    }

    pub fn setPosition(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_position", .{position});
    }

    pub fn setRotation(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_rotation", .{radians});
    }

    pub fn setRotationDegrees(self: @This(), degrees: f64) !void {
        try support.callVoid(self, "set_rotation_degrees", .{degrees});
    }

    pub fn setSkew(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_skew", .{radians});
    }

    pub fn setScale(self: @This(), scale: abi.Vector2) !void {
        try support.callVoid(self, "set_scale", .{scale});
    }

    pub fn getPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_position", .{});
    }

    pub fn getRotation(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation", .{});
    }

    pub fn getRotationDegrees(self: @This()) !f64 {
        return support.call(self, f64, "get_rotation_degrees", .{});
    }

    pub fn getSkew(self: @This()) !f64 {
        return support.call(self, f64, "get_skew", .{});
    }

    pub fn getScale(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_scale", .{});
    }

    pub fn rotate(self: @This(), radians: f64) !void {
        try support.callVoid(self, "rotate", .{radians});
    }

    pub fn moveLocalX(self: @This(), delta: f64, scaled: bool) !void {
        try support.callVoid(self, "move_local_x", .{ delta, scaled });
    }

    pub fn moveLocalY(self: @This(), delta: f64, scaled: bool) !void {
        try support.callVoid(self, "move_local_y", .{ delta, scaled });
    }

    pub fn translate(self: @This(), offset: abi.Vector2) !void {
        try support.callVoid(self, "translate", .{offset});
    }

    pub fn globalTranslate(self: @This(), offset: abi.Vector2) !void {
        try support.callVoid(self, "global_translate", .{offset});
    }

    pub fn applyScale(self: @This(), ratio: abi.Vector2) !void {
        try support.callVoid(self, "apply_scale", .{ratio});
    }

    pub fn setGlobalPosition(self: @This(), position: abi.Vector2) !void {
        try support.callVoid(self, "set_global_position", .{position});
    }

    pub fn getGlobalPosition(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_position", .{});
    }

    pub fn setGlobalRotation(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_global_rotation", .{radians});
    }

    pub fn setGlobalRotationDegrees(self: @This(), degrees: f64) !void {
        try support.callVoid(self, "set_global_rotation_degrees", .{degrees});
    }

    pub fn getGlobalRotation(self: @This()) !f64 {
        return support.call(self, f64, "get_global_rotation", .{});
    }

    pub fn getGlobalRotationDegrees(self: @This()) !f64 {
        return support.call(self, f64, "get_global_rotation_degrees", .{});
    }

    pub fn setGlobalSkew(self: @This(), radians: f64) !void {
        try support.callVoid(self, "set_global_skew", .{radians});
    }

    pub fn getGlobalSkew(self: @This()) !f64 {
        return support.call(self, f64, "get_global_skew", .{});
    }

    pub fn setGlobalScale(self: @This(), scale: abi.Vector2) !void {
        try support.callVoid(self, "set_global_scale", .{scale});
    }

    pub fn getGlobalScale(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_global_scale", .{});
    }

    pub fn lookAt(self: @This(), point: abi.Vector2) !void {
        try support.callVoid(self, "look_at", .{point});
    }

    pub fn getAngleTo(self: @This(), point: abi.Vector2) !f64 {
        return support.call(self, f64, "get_angle_to", .{point});
    }

    pub fn toLocal(self: @This(), global_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "to_local", .{global_point});
    }

    pub fn toGlobal(self: @This(), local_point: abi.Vector2) !abi.Vector2 {
        return support.call(self, abi.Vector2, "to_global", .{local_point});
    }

    pub fn setTexture(self: @This(), texture: ?Texture2D) !void {
        try support.callVoid(self, "set_texture", .{texture});
    }

    pub fn getTexture(self: @This()) !?Texture2D {
        return support.call(self, ?Texture2D, "get_texture", .{});
    }

    pub fn setCentered(self: @This(), centered: bool) !void {
        try support.callVoid(self, "set_centered", .{centered});
    }

    pub fn isCentered(self: @This()) !bool {
        return support.call(self, bool, "is_centered", .{});
    }

    pub fn setOffset(self: @This(), offset: abi.Vector2) !void {
        try support.callVoid(self, "set_offset", .{offset});
    }

    pub fn getOffset(self: @This()) !abi.Vector2 {
        return support.call(self, abi.Vector2, "get_offset", .{});
    }

    pub fn setFlipH(self: @This(), flip_h: bool) !void {
        try support.callVoid(self, "set_flip_h", .{flip_h});
    }

    pub fn isFlippedH(self: @This()) !bool {
        return support.call(self, bool, "is_flipped_h", .{});
    }

    pub fn setFlipV(self: @This(), flip_v: bool) !void {
        try support.callVoid(self, "set_flip_v", .{flip_v});
    }

    pub fn isFlippedV(self: @This()) !bool {
        return support.call(self, bool, "is_flipped_v", .{});
    }

    pub fn setRegionEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_region_enabled", .{enabled});
    }

    pub fn isRegionEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_region_enabled", .{});
    }

    pub fn isPixelOpaque(self: @This(), pos: abi.Vector2) !bool {
        return support.call(self, bool, "is_pixel_opaque", .{pos});
    }

    pub fn setRegionFilterClipEnabled(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_region_filter_clip_enabled", .{enabled});
    }

    pub fn isRegionFilterClipEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_region_filter_clip_enabled", .{});
    }

    pub fn setFrame(self: @This(), frame: i64) !void {
        try support.callVoid(self, "set_frame", .{frame});
    }

    pub fn getFrame(self: @This()) !i64 {
        return support.call(self, i64, "get_frame", .{});
    }

    pub fn setVframes(self: @This(), vframes: i64) !void {
        try support.callVoid(self, "set_vframes", .{vframes});
    }

    pub fn getVframes(self: @This()) !i64 {
        return support.call(self, i64, "get_vframes", .{});
    }

    pub fn setHframes(self: @This(), hframes: i64) !void {
        try support.callVoid(self, "set_hframes", .{hframes});
    }

    pub fn getHframes(self: @This()) !i64 {
        return support.call(self, i64, "get_hframes", .{});
    }
};

pub const Node3D = extern struct {
    owner: u64,

    pub const godot_class = "Node3D";
    pub const emitSignal = support.emitSignal;

    pub const RotationEditMode = enum(i64) {
        rotation_edit_mode_euler = 0,
        rotation_edit_mode_quaternion = 1,
        rotation_edit_mode_basis = 2,
    };

    pub fn asNode(self: @This()) Node {
        return .{ .owner = self.owner };
    }

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void {
        try support.callVoid(self, "add_sibling", .{ sibling, force_readable_name });
    }

    pub fn setName(self: @This(), name: []const u8) !void {
        try support.callVoid(self, "set_name", .{name});
    }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void {
        try support.callVoid(self, "add_child", .{ node, force_readable_name, internal });
    }

    pub fn removeChild(self: @This(), node: Node) !void {
        try support.callVoid(self, "remove_child", .{node});
    }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void {
        try support.callVoid(self, "reparent", .{ new_parent, keep_global_transform });
    }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_child_count", .{include_internal});
    }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node {
        return support.call(self, ?Node, "get_child", .{ idx, include_internal });
    }

    pub fn hasNode(self: @This(), path: []const u8) !bool {
        return support.call(self, bool, "has_node", .{path});
    }

    pub fn getNode(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node", .{path});
    }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node {
        return support.call(self, ?Node, "get_node_or_null", .{path});
    }

    pub fn getParent(self: @This()) !?Node {
        return support.call(self, ?Node, "get_parent", .{});
    }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node {
        return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned });
    }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node {
        return support.call(self, ?Node, "find_parent", .{pattern});
    }

    pub fn isInsideTree(self: @This()) !bool {
        return support.call(self, bool, "is_inside_tree", .{});
    }

    pub fn isAncestorOf(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_ancestor_of", .{node});
    }

    pub fn isGreaterThan(self: @This(), node: Node) !bool {
        return support.call(self, bool, "is_greater_than", .{node});
    }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void {
        try support.callVoid(self, "add_to_group", .{ group, persistent });
    }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void {
        try support.callVoid(self, "remove_from_group", .{group});
    }

    pub fn isInGroup(self: @This(), group: []const u8) !bool {
        return support.call(self, bool, "is_in_group", .{group});
    }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void {
        try support.callVoid(self, "move_child", .{ child_node, to_index });
    }

    pub fn setOwner(self: @This(), owner: ?Node) !void {
        try support.callVoid(self, "set_owner", .{owner});
    }

    pub fn getOwner(self: @This()) !?Node {
        return support.call(self, ?Node, "get_owner", .{});
    }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 {
        return support.call(self, i64, "get_index", .{include_internal});
    }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_physics_process", .{enable});
    }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_physics_process_delta_time", .{});
    }

    pub fn isPhysicsProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_physics_processing", .{});
    }

    pub fn getProcessDeltaTime(self: @This()) !f64 {
        return support.call(self, f64, "get_process_delta_time", .{});
    }

    pub fn setProcess(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process", .{enable});
    }

    pub fn setProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_process_priority", .{priority});
    }

    pub fn getProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_process_priority", .{});
    }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void {
        try support.callVoid(self, "set_physics_process_priority", .{priority});
    }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 {
        return support.call(self, i64, "get_physics_process_priority", .{});
    }

    pub fn isProcessing(self: @This()) !bool {
        return support.call(self, bool, "is_processing", .{});
    }

    pub fn setProcessInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_input", .{enable});
    }

    pub fn isProcessingInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_input", .{});
    }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_process_unhandled_input", .{enable});
    }

    pub fn isProcessingUnhandledInput(self: @This()) !bool {
        return support.call(self, bool, "is_processing_unhandled_input", .{});
    }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void {
        try support.callVoid(self, "set_process_mode", .{mode});
    }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode {
        return support.call(self, Node.ProcessMode, "get_process_mode", .{});
    }

    pub fn canProcess(self: @This()) !bool {
        return support.call(self, bool, "can_process", .{});
    }

    pub fn createTween(self: @This()) !Tween {
        return support.call(self, Tween, "create_tween", .{});
    }

    pub fn getViewport(self: @This()) !?Viewport {
        return support.call(self, ?Viewport, "get_viewport", .{});
    }

    pub fn queueFree(self: @This()) !void {
        try support.callVoid(self, "queue_free", .{});
    }

    pub fn requestReady(self: @This()) !void {
        try support.callVoid(self, "request_ready", .{});
    }

    pub fn isNodeReady(self: @This()) !bool {
        return support.call(self, bool, "is_node_ready", .{});
    }

    pub fn setRotationOrder(self: @This(), order: EulerOrder) !void {
        try support.callVoid(self, "set_rotation_order", .{order});
    }

    pub fn getRotationOrder(self: @This()) !EulerOrder {
        return support.call(self, EulerOrder, "get_rotation_order", .{});
    }

    pub fn setRotationEditMode(self: @This(), edit_mode: Node3D.RotationEditMode) !void {
        try support.callVoid(self, "set_rotation_edit_mode", .{edit_mode});
    }

    pub fn getRotationEditMode(self: @This()) !Node3D.RotationEditMode {
        return support.call(self, Node3D.RotationEditMode, "get_rotation_edit_mode", .{});
    }

    pub fn getParentNode3D(self: @This()) !?Node3D {
        return support.call(self, ?Node3D, "get_parent_node_3d", .{});
    }

    pub fn setIgnoreTransformNotification(self: @This(), enabled: bool) !void {
        try support.callVoid(self, "set_ignore_transform_notification", .{enabled});
    }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_as_top_level", .{enable});
    }

    pub fn isSetAsTopLevel(self: @This()) !bool {
        return support.call(self, bool, "is_set_as_top_level", .{});
    }

    pub fn setDisableScale(self: @This(), disable: bool) !void {
        try support.callVoid(self, "set_disable_scale", .{disable});
    }

    pub fn isScaleDisabled(self: @This()) !bool {
        return support.call(self, bool, "is_scale_disabled", .{});
    }

    pub fn forceUpdateTransform(self: @This()) !void {
        try support.callVoid(self, "force_update_transform", .{});
    }

    pub fn setVisibilityParent(self: @This(), path: []const u8) !void {
        try support.callVoid(self, "set_visibility_parent", .{path});
    }

    pub fn updateGizmos(self: @This()) !void {
        try support.callVoid(self, "update_gizmos", .{});
    }

    pub fn clearGizmos(self: @This()) !void {
        try support.callVoid(self, "clear_gizmos", .{});
    }

    pub fn clearSubgizmoSelection(self: @This()) !void {
        try support.callVoid(self, "clear_subgizmo_selection", .{});
    }

    pub fn setVisible(self: @This(), visible: bool) !void {
        try support.callVoid(self, "set_visible", .{visible});
    }

    pub fn isVisible(self: @This()) !bool {
        return support.call(self, bool, "is_visible", .{});
    }

    pub fn isVisibleInTree(self: @This()) !bool {
        return support.call(self, bool, "is_visible_in_tree", .{});
    }

    pub fn show(self: @This()) !void {
        try support.callVoid(self, "show", .{});
    }

    pub fn hide(self: @This()) !void {
        try support.callVoid(self, "hide", .{});
    }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_local_transform", .{enable});
    }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_local_transform_notification_enabled", .{});
    }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void {
        try support.callVoid(self, "set_notify_transform", .{enable});
    }

    pub fn isTransformNotificationEnabled(self: @This()) !bool {
        return support.call(self, bool, "is_transform_notification_enabled", .{});
    }

    pub fn rotateX(self: @This(), angle: f64) !void {
        try support.callVoid(self, "rotate_x", .{angle});
    }

    pub fn rotateY(self: @This(), angle: f64) !void {
        try support.callVoid(self, "rotate_y", .{angle});
    }

    pub fn rotateZ(self: @This(), angle: f64) !void {
        try support.callVoid(self, "rotate_z", .{angle});
    }

    pub fn orthonormalize(self: @This()) !void {
        try support.callVoid(self, "orthonormalize", .{});
    }

    pub fn setIdentity(self: @This()) !void {
        try support.callVoid(self, "set_identity", .{});
    }
};

pub const Texture2D = extern struct {
    owner: u64,

    pub const godot_class = "Texture2D";
    pub const emitSignal = support.emitSignal;
};

pub const Viewport = extern struct {
    owner: u64,

    pub const godot_class = "Viewport";
    pub const emitSignal = support.emitSignal;
};

pub const Tween = extern struct {
    owner: u64,

    pub const godot_class = "Tween";
    pub const emitSignal = support.emitSignal;
};
