// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const AccessibilityServer = extern struct {
    owner: u64,

    pub const godot_class = "AccessibilityServer";
    pub const emitSignal = support.emitSignal;

    pub const AccessibilityLiveMode = enum(i64) {
        live_off = 0,
        live_polite = 1,
        live_assertive = 2,
    };
};
