// Generated by tools/generate_bindings.zig. Do not edit.
const abi = @import("../../abi.zig");
const support = @import("../../class_support.zig");
const Node = @import("node.zig").Node;
const Window = @import("window.zig").Window;
const SceneTree = @import("scene_tree.zig").SceneTree;
const Tween = @import("tween.zig").Tween;
const Viewport = @import("viewport.zig").Viewport;
const MultiplayerAPI = @import("multiplayer_api.zig").MultiplayerAPI;
const MultiMesh = @import("multi_mesh.zig").MultiMesh;
const Texture2D = @import("texture_2d.zig").Texture2D;
const CanvasLayer = @import("canvas_layer.zig").CanvasLayer;
const World2D = @import("world_2d.zig").World2D;
const Material = @import("material.zig").Material;
const InputEvent = @import("input_event.zig").InputEvent;

pub const CanvasItem = extern struct {
    owner: u64,

    pub const godot_class = "CanvasItem";
    pub const emitSignal = support.emitSignal;

    pub const TextureFilter = enum(i64) {
        parent_node = 0,
        nearest = 1,
        linear = 2,
        nearest_with_mipmaps = 3,
        linear_with_mipmaps = 4,
        nearest_with_mipmaps_anisotropic = 5,
        linear_with_mipmaps_anisotropic = 6,
        max = 7,
    };

    pub const TextureRepeat = enum(i64) {
        parent_node = 0,
        disabled = 1,
        enabled = 2,
        mirror = 3,
        max = 4,
    };

    pub const ClipChildrenMode = enum(i64) {
        disabled = 0,
        only = 1,
        and_draw = 2,
        max = 3,
    };

    pub const OversamplingWithScale = enum(i64) {
        parent_node = 0,
        disabled = 1,
        enabled = 2,
        max = 3,
    };

    pub fn asNode(self: @This()) Node { return .{ .owner = self.owner }; }

    pub fn setVisible(self: @This(), visible: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_visible", 2586408642, .{visible}); }

    pub fn isVisible(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_visible", 36873697, .{}); }

    pub fn isVisibleInTree(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_visible_in_tree", 36873697, .{}); }

    pub fn show(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "show", 3218959716, .{}); }

    pub fn hide(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "hide", 3218959716, .{}); }

    pub fn queueRedraw(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "queue_redraw", 3218959716, .{}); }

    pub fn moveToFront(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "move_to_front", 3218959716, .{}); }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_as_top_level", 2586408642, .{enable}); }

    pub fn isSetAsTopLevel(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_set_as_top_level", 36873697, .{}); }

    pub fn setLightMask(self: @This(), light_mask: i64) !void { return support.callVoid(self, "set_light_mask", .{light_mask}); }

    pub fn getLightMask(self: @This()) !i64 { return support.call(self, i64, "get_light_mask", .{}); }

    pub fn setZIndex(self: @This(), z_index: i64) !void { return support.callVoid(self, "set_z_index", .{z_index}); }

    pub fn getZIndex(self: @This()) !i64 { return support.call(self, i64, "get_z_index", .{}); }

    pub fn setZAsRelative(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_z_as_relative", 2586408642, .{enable}); }

    pub fn isZRelative(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_z_relative", 36873697, .{}); }

    pub fn setYSortEnabled(self: @This(), enabled: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_y_sort_enabled", 2586408642, .{enabled}); }

    pub fn isYSortEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_y_sort_enabled", 36873697, .{}); }

    pub fn setDrawBehindParent(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_draw_behind_parent", 2586408642, .{enable}); }

    pub fn isDrawBehindParentEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_draw_behind_parent_enabled", 36873697, .{}); }

    pub fn drawMultimesh(self: @This(), multimesh: MultiMesh, texture: ?Texture2D) !void { return support.callVoid(self, "draw_multimesh", .{ multimesh, texture }); }

    pub fn drawSetTransform(self: @This(), position: abi.Vector2(f64), rotation: f64, scale: abi.Vector2(f64)) !void { return support.callVoid(self, "draw_set_transform", .{ position, rotation, scale }); }

    pub fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "draw_animation_slice", 3112831842, .{ animation_length, slice_begin, slice_end, offset }); }

    pub fn drawEndAnimation(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "draw_end_animation", 3218959716, .{}); }

    pub fn getLocalMousePosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "CanvasItem", "get_local_mouse_position", 3341600327, .{}); }

    pub fn getGlobalMousePosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "CanvasItem", "get_global_mouse_position", 3341600327, .{}); }

    pub fn getCanvasLayerNode(self: @This()) !?CanvasLayer { return support.call(self, ?CanvasLayer, "get_canvas_layer_node", .{}); }

    pub fn getWorld2D(self: @This()) !?World2D { return support.call(self, ?World2D, "get_world_2d", .{}); }

    pub fn setMaterial(self: @This(), material: ?Material) !void { return support.callVoid(self, "set_material", .{material}); }

    pub fn getMaterial(self: @This()) !?Material { return support.call(self, ?Material, "get_material", .{}); }

    pub fn setUseParentMaterial(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_use_parent_material", 2586408642, .{enable}); }

    pub fn getUseParentMaterial(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "get_use_parent_material", 36873697, .{}); }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_notify_local_transform", 2586408642, .{enable}); }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_local_transform_notification_enabled", 36873697, .{}); }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_notify_transform", 2586408642, .{enable}); }

    pub fn isTransformNotificationEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "CanvasItem", "is_transform_notification_enabled", 36873697, .{}); }

    pub fn forceUpdateTransform(self: @This()) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "force_update_transform", 3218959716, .{}); }

    pub fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2(f64)) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "CanvasItem", "make_canvas_position_local", 2656412154, .{viewport_point}); }

    pub fn makeInputLocal(self: @This(), event: InputEvent) !InputEvent { return support.call(self, InputEvent, "make_input_local", .{event}); }

    pub fn setVisibilityLayer(self: @This(), layer: i64) !void { return support.callVoid(self, "set_visibility_layer", .{layer}); }

    pub fn getVisibilityLayer(self: @This()) !i64 { return support.call(self, i64, "get_visibility_layer", .{}); }

    pub fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void { return support.callVoid(self, "set_visibility_layer_bit", .{ layer, enabled }); }

    pub fn getVisibilityLayerBit(self: @This(), layer: i64) !bool { return support.call(self, bool, "get_visibility_layer_bit", .{layer}); }

    pub fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_texture_filter", 1037999706, .{mode}); }

    pub fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter { return support.ptrcallMethod(self, CanvasItem.TextureFilter, "CanvasItem", "get_texture_filter", 121960042, .{}); }

    pub fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_texture_repeat", 1716472974, .{mode}); }

    pub fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat { return support.ptrcallMethod(self, CanvasItem.TextureRepeat, "CanvasItem", "get_texture_repeat", 2667158319, .{}); }

    pub fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_clip_children_mode", 1319393776, .{mode}); }

    pub fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode { return support.ptrcallMethod(self, CanvasItem.ClipChildrenMode, "CanvasItem", "get_clip_children_mode", 3581808349, .{}); }

    pub fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void { return support.ptrcallMethodVoid(self, "CanvasItem", "set_oversampling_with_scale", 872218804, .{enabled}); }

    pub fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale { return support.ptrcallMethod(self, CanvasItem.OversamplingWithScale, "CanvasItem", "get_oversampling_with_scale", 2026097197, .{}); }

    pub inline fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void { return self.asNode().addSibling(sibling, force_readable_name); }

    pub inline fn setName(self: @This(), name: []const u8) !void { return self.asNode().setName(name); }

    pub inline fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void { return self.asNode().addChild(node, force_readable_name, internal); }

    pub inline fn removeChild(self: @This(), node: Node) !void { return self.asNode().removeChild(node); }

    pub inline fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void { return self.asNode().reparent(new_parent, keep_global_transform); }

    pub inline fn getChildCount(self: @This(), include_internal: bool) !i64 { return self.asNode().getChildCount(include_internal); }

    pub inline fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node { return self.asNode().getChild(idx, include_internal); }

    pub inline fn hasNode(self: @This(), path: []const u8) !bool { return self.asNode().hasNode(path); }

    pub inline fn getNode(self: @This(), path: []const u8) !?Node { return self.asNode().getNode(path); }

    pub inline fn getNodeOrNull(self: @This(), path: []const u8) !?Node { return self.asNode().getNodeOrNull(path); }

    pub inline fn getParent(self: @This()) !?Node { return self.asNode().getParent(); }

    pub inline fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node { return self.asNode().findChild(pattern, recursive, owned); }

    pub inline fn findParent(self: @This(), pattern: []const u8) !?Node { return self.asNode().findParent(pattern); }

    pub inline fn hasNodeAndResource(self: @This(), path: []const u8) !bool { return self.asNode().hasNodeAndResource(path); }

    pub inline fn isInsideTree(self: @This()) !bool { return self.asNode().isInsideTree(); }

    pub inline fn isPartOfEditedScene(self: @This()) !bool { return self.asNode().isPartOfEditedScene(); }

    pub inline fn isAncestorOf(self: @This(), node: Node) !bool { return self.asNode().isAncestorOf(node); }

    pub inline fn isGreaterThan(self: @This(), node: Node) !bool { return self.asNode().isGreaterThan(node); }

    pub inline fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void { return self.asNode().addToGroup(group, persistent); }

    pub inline fn removeFromGroup(self: @This(), group: []const u8) !void { return self.asNode().removeFromGroup(group); }

    pub inline fn isInGroup(self: @This(), group: []const u8) !bool { return self.asNode().isInGroup(group); }

    pub inline fn moveChild(self: @This(), child_node: Node, to_index: i64) !void { return self.asNode().moveChild(child_node, to_index); }

    pub inline fn setOwner(self: @This(), owner: ?Node) !void { return self.asNode().setOwner(owner); }

    pub inline fn getOwner(self: @This()) !?Node { return self.asNode().getOwner(); }

    pub inline fn getIndex(self: @This(), include_internal: bool) !i64 { return self.asNode().getIndex(include_internal); }

    pub inline fn printTree(self: @This()) !void { return self.asNode().printTree(); }

    pub inline fn printTreePretty(self: @This()) !void { return self.asNode().printTreePretty(); }

    pub inline fn setSceneFilePath(self: @This(), scene_file_path: []const u8) !void { return self.asNode().setSceneFilePath(scene_file_path); }

    pub inline fn propagateNotification(self: @This(), what: i64) !void { return self.asNode().propagateNotification(what); }

    pub inline fn setPhysicsProcess(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcess(enable); }

    pub inline fn getPhysicsProcessDeltaTime(self: @This()) !f64 { return self.asNode().getPhysicsProcessDeltaTime(); }

    pub inline fn isPhysicsProcessing(self: @This()) !bool { return self.asNode().isPhysicsProcessing(); }

    pub inline fn getProcessDeltaTime(self: @This()) !f64 { return self.asNode().getProcessDeltaTime(); }

    pub inline fn setProcess(self: @This(), enable: bool) !void { return self.asNode().setProcess(enable); }

    pub inline fn setProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setProcessPriority(priority); }

    pub inline fn getProcessPriority(self: @This()) !i64 { return self.asNode().getProcessPriority(); }

    pub inline fn setPhysicsProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setPhysicsProcessPriority(priority); }

    pub inline fn getPhysicsProcessPriority(self: @This()) !i64 { return self.asNode().getPhysicsProcessPriority(); }

    pub inline fn isProcessing(self: @This()) !bool { return self.asNode().isProcessing(); }

    pub inline fn setProcessInput(self: @This(), enable: bool) !void { return self.asNode().setProcessInput(enable); }

    pub inline fn isProcessingInput(self: @This()) !bool { return self.asNode().isProcessingInput(); }

    pub inline fn setProcessShortcutInput(self: @This(), enable: bool) !void { return self.asNode().setProcessShortcutInput(enable); }

    pub inline fn isProcessingShortcutInput(self: @This()) !bool { return self.asNode().isProcessingShortcutInput(); }

    pub inline fn setProcessUnhandledInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledInput(enable); }

    pub inline fn isProcessingUnhandledInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledInput(); }

    pub inline fn setProcessUnhandledKeyInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledKeyInput(enable); }

    pub inline fn isProcessingUnhandledKeyInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledKeyInput(); }

    pub inline fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void { return self.asNode().setProcessMode(mode); }

    pub inline fn getProcessMode(self: @This()) !Node.ProcessMode { return self.asNode().getProcessMode(); }

    pub inline fn canProcess(self: @This()) !bool { return self.asNode().canProcess(); }

    pub inline fn setProcessThreadGroup(self: @This(), mode: Node.ProcessThreadGroup) !void { return self.asNode().setProcessThreadGroup(mode); }

    pub inline fn getProcessThreadGroup(self: @This()) !Node.ProcessThreadGroup { return self.asNode().getProcessThreadGroup(); }

    pub inline fn setProcessThreadMessages(self: @This(), flags: Node.ProcessThreadMessages) !void { return self.asNode().setProcessThreadMessages(flags); }

    pub inline fn getProcessThreadMessages(self: @This()) !Node.ProcessThreadMessages { return self.asNode().getProcessThreadMessages(); }

    pub inline fn setProcessThreadGroupOrder(self: @This(), order: i64) !void { return self.asNode().setProcessThreadGroupOrder(order); }

    pub inline fn getProcessThreadGroupOrder(self: @This()) !i64 { return self.asNode().getProcessThreadGroupOrder(); }

    pub inline fn queueAccessibilityUpdate(self: @This()) !void { return self.asNode().queueAccessibilityUpdate(); }

    pub inline fn setDisplayFolded(self: @This(), fold: bool) !void { return self.asNode().setDisplayFolded(fold); }

    pub inline fn isDisplayedFolded(self: @This()) !bool { return self.asNode().isDisplayedFolded(); }

    pub inline fn setProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setProcessInternal(enable); }

    pub inline fn isProcessingInternal(self: @This()) !bool { return self.asNode().isProcessingInternal(); }

    pub inline fn setPhysicsProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcessInternal(enable); }

    pub inline fn isPhysicsProcessingInternal(self: @This()) !bool { return self.asNode().isPhysicsProcessingInternal(); }

    pub inline fn setPhysicsInterpolationMode(self: @This(), mode: Node.PhysicsInterpolationMode) !void { return self.asNode().setPhysicsInterpolationMode(mode); }

    pub inline fn getPhysicsInterpolationMode(self: @This()) !Node.PhysicsInterpolationMode { return self.asNode().getPhysicsInterpolationMode(); }

    pub inline fn isPhysicsInterpolated(self: @This()) !bool { return self.asNode().isPhysicsInterpolated(); }

    pub inline fn isPhysicsInterpolatedAndEnabled(self: @This()) !bool { return self.asNode().isPhysicsInterpolatedAndEnabled(); }

    pub inline fn resetPhysicsInterpolation(self: @This()) !void { return self.asNode().resetPhysicsInterpolation(); }

    pub inline fn setAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return self.asNode().setAutoTranslateMode(mode); }

    pub inline fn getAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return self.asNode().getAutoTranslateMode(); }

    pub inline fn canAutoTranslate(self: @This()) !bool { return self.asNode().canAutoTranslate(); }

    pub inline fn setTranslationDomainInherited(self: @This()) !void { return self.asNode().setTranslationDomainInherited(); }

    pub inline fn getWindow(self: @This()) !?Window { return self.asNode().getWindow(); }

    pub inline fn getLastExclusiveWindow(self: @This()) !?Window { return self.asNode().getLastExclusiveWindow(); }

    pub inline fn getTree(self: @This()) !?SceneTree { return self.asNode().getTree(); }

    pub inline fn createTween(self: @This()) !Tween { return self.asNode().createTween(); }

    pub inline fn duplicate(self: @This(), flags: i64) !?Node { return self.asNode().duplicate(flags); }

    pub inline fn replaceBy(self: @This(), node: Node, keep_groups: bool) !void { return self.asNode().replaceBy(node, keep_groups); }

    pub inline fn setSceneInstanceLoadPlaceholder(self: @This(), load_placeholder: bool) !void { return self.asNode().setSceneInstanceLoadPlaceholder(load_placeholder); }

    pub inline fn getSceneInstanceLoadPlaceholder(self: @This()) !bool { return self.asNode().getSceneInstanceLoadPlaceholder(); }

    pub inline fn setEditableInstance(self: @This(), node: Node, is_editable: bool) !void { return self.asNode().setEditableInstance(node, is_editable); }

    pub inline fn isEditableInstance(self: @This(), node: ?Node) !bool { return self.asNode().isEditableInstance(node); }

    pub inline fn getViewport(self: @This()) !?Viewport { return self.asNode().getViewport(); }

    pub inline fn queueFree(self: @This()) !void { return self.asNode().queueFree(); }

    pub inline fn requestReady(self: @This()) !void { return self.asNode().requestReady(); }

    pub inline fn isNodeReady(self: @This()) !bool { return self.asNode().isNodeReady(); }

    pub inline fn setMultiplayerAuthority(self: @This(), id: i64, recursive: bool) !void { return self.asNode().setMultiplayerAuthority(id, recursive); }

    pub inline fn getMultiplayerAuthority(self: @This()) !i64 { return self.asNode().getMultiplayerAuthority(); }

    pub inline fn isMultiplayerAuthority(self: @This()) !bool { return self.asNode().isMultiplayerAuthority(); }

    pub inline fn getMultiplayer(self: @This()) !?MultiplayerAPI { return self.asNode().getMultiplayer(); }

    pub inline fn setEditorDescription(self: @This(), editor_description: []const u8) !void { return self.asNode().setEditorDescription(editor_description); }

    pub inline fn setUniqueNameInOwner(self: @This(), enable: bool) !void { return self.asNode().setUniqueNameInOwner(enable); }

    pub inline fn isUniqueNameInOwner(self: @This()) !bool { return self.asNode().isUniqueNameInOwner(); }

    pub inline fn updateConfigurationWarnings(self: @This()) !void { return self.asNode().updateConfigurationWarnings(); }

    pub inline fn notifyDeferredThreadGroup(self: @This(), what: i64) !void { return self.asNode().notifyDeferredThreadGroup(what); }

    pub inline fn notifyThreadSafe(self: @This(), what: i64) !void { return self.asNode().notifyThreadSafe(what); }
};
