// Generated by tools/generate_bindings.zig. Do not edit.
const abi = @import("../../abi.zig");
const support = @import("../../class_support.zig");
const Side = @import("../global_enums.zig").Side;
const Node = @import("node.zig").Node;
const CanvasItem = @import("canvas_item.zig").CanvasItem;
const Window = @import("window.zig").Window;
const SceneTree = @import("scene_tree.zig").SceneTree;
const Tween = @import("tween.zig").Tween;
const Viewport = @import("viewport.zig").Viewport;
const MultiplayerAPI = @import("multiplayer_api.zig").MultiplayerAPI;
const MultiMesh = @import("multi_mesh.zig").MultiMesh;
const Texture2D = @import("texture_2d.zig").Texture2D;
const CanvasLayer = @import("canvas_layer.zig").CanvasLayer;
const World2D = @import("world_2d.zig").World2D;
const Material = @import("material.zig").Material;
const InputEvent = @import("input_event.zig").InputEvent;
const Theme = @import("theme.zig").Theme;
const StyleBox = @import("style_box.zig").StyleBox;
const Font = @import("font.zig").Font;
const AccessibilityServer = @import("accessibility_server.zig").AccessibilityServer;

pub const Control = extern struct {
    owner: u64,

    pub const godot_class = "Control";
    pub const emitSignal = support.emitSignal;

    pub const LayoutPreset = enum(i64) {
        top_left = 0,
        top_right = 1,
        bottom_left = 2,
        bottom_right = 3,
        center_left = 4,
        center_top = 5,
        center_right = 6,
        center_bottom = 7,
        center = 8,
        left_wide = 9,
        top_wide = 10,
        right_wide = 11,
        bottom_wide = 12,
        vcenter_wide = 13,
        hcenter_wide = 14,
        full_rect = 15,
    };

    pub const LayoutPresetMode = enum(i64) {
        minsize = 0,
        keep_width = 1,
        keep_height = 2,
        keep_size = 3,
    };

    pub const FocusMode = enum(i64) {
        none = 0,
        click = 1,
        all = 2,
        accessibility = 3,
    };

    pub const FocusBehaviorRecursive = enum(i64) {
        focus_behavior_inherited = 0,
        focus_behavior_disabled = 1,
        focus_behavior_enabled = 2,
    };

    pub const SizeFlags = enum(i64) {
        shrink_begin = 0,
        fill = 1,
        expand = 2,
        expand_fill = 3,
        shrink_center = 4,
        shrink_end = 8,
        _,
    };

    pub const GrowDirection = enum(i64) {
        begin = 0,
        end = 1,
        both = 2,
    };

    pub const CursorShape = enum(i64) {
        cursor_arrow = 0,
        cursor_ibeam = 1,
        cursor_pointing_hand = 2,
        cursor_cross = 3,
        cursor_wait = 4,
        cursor_busy = 5,
        cursor_drag = 6,
        cursor_can_drop = 7,
        cursor_forbidden = 8,
        cursor_vsize = 9,
        cursor_hsize = 10,
        cursor_bdiagsize = 11,
        cursor_fdiagsize = 12,
        cursor_move = 13,
        cursor_vsplit = 14,
        cursor_hsplit = 15,
        cursor_help = 16,
    };

    pub const MouseFilter = enum(i64) {
        stop = 0,
        pass = 1,
        ignore = 2,
    };

    pub const MouseBehaviorRecursive = enum(i64) {
        mouse_behavior_inherited = 0,
        mouse_behavior_disabled = 1,
        mouse_behavior_enabled = 2,
    };

    pub const LayoutDirection = enum(i64) {
        inherited = 0,
        application_locale = 1,
        ltr = 2,
        rtl = 3,
        system_locale = 4,
        max = 5,
        pub const locale: @This() = .application_locale;
    };

    pub fn asNode(self: @This()) Node { return .{ .owner = self.owner }; }

    pub fn asCanvasItem(self: @This()) CanvasItem { return .{ .owner = self.owner }; }

    pub fn acceptEvent(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "accept_event", 3218959716, .{}); }

    pub fn getMaximumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_maximum_size", 3341600327, .{}); }

    pub fn getCombinedMaximumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_combined_maximum_size", 3341600327, .{}); }

    pub fn getMinimumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_minimum_size", 3341600327, .{}); }

    pub fn getCombinedMinimumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_combined_minimum_size", 3341600327, .{}); }

    pub fn setPropagateMaximumSize(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_propagate_maximum_size", 2586408642, .{enable}); }

    pub fn isPropagatingMaximumSize(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_propagating_maximum_size", 2240911060, .{}); }

    pub fn getBoundMinimumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_bound_minimum_size", 3341600327, .{}); }

    pub fn setAnchorsPreset(self: @This(), preset: Control.LayoutPreset, keep_offsets: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_anchors_preset", 509135270, .{ preset, keep_offsets }); }

    pub fn setOffsetsPreset(self: @This(), preset: Control.LayoutPreset, resize_mode: Control.LayoutPresetMode, margin: i64) !void { return support.callVoid(self, "set_offsets_preset", .{ preset, resize_mode, margin }); }

    pub fn setAnchorsAndOffsetsPreset(self: @This(), preset: Control.LayoutPreset, resize_mode: Control.LayoutPresetMode, margin: i64) !void { return support.callVoid(self, "set_anchors_and_offsets_preset", .{ preset, resize_mode, margin }); }

    pub fn setAnchor(self: @This(), side: Side, anchor: f64, keep_offset: bool, push_opposite_anchor: bool) !void { return support.callVoid(self, "set_anchor", .{ side, anchor, keep_offset, push_opposite_anchor }); }

    pub fn getAnchor(self: @This(), side: Side) !f64 { return support.call(self, f64, "get_anchor", .{side}); }

    pub fn setOffset(self: @This(), side: Side, offset: f64) !void { return support.callVoid(self, "set_offset", .{ side, offset }); }

    pub fn getOffset(self: @This(), offset: Side) !f64 { return support.call(self, f64, "get_offset", .{offset}); }

    pub fn setAnchorAndOffset(self: @This(), side: Side, anchor: f64, offset: f64, push_opposite_anchor: bool) !void { return support.callVoid(self, "set_anchor_and_offset", .{ side, anchor, offset, push_opposite_anchor }); }

    pub fn setBegin(self: @This(), position: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_begin", 743155724, .{position}); }

    pub fn setEnd(self: @This(), position: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_end", 743155724, .{position}); }

    pub fn setPosition(self: @This(), position: abi.Vector2(f64), keep_offsets: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_position", 2436320129, .{ position, keep_offsets }); }

    pub fn setSize(self: @This(), size: abi.Vector2(f64), keep_offsets: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_size", 2436320129, .{ size, keep_offsets }); }

    pub fn resetSize(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "reset_size", 3218959716, .{}); }

    pub fn setCustomMaximumSize(self: @This(), size: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_custom_maximum_size", 743155724, .{size}); }

    pub fn setCustomMinimumSize(self: @This(), size: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_custom_minimum_size", 743155724, .{size}); }

    pub fn setGlobalPosition(self: @This(), position: abi.Vector2(f64), keep_offsets: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_global_position", 2436320129, .{ position, keep_offsets }); }

    pub fn setRotation(self: @This(), radians: f64) !void { return support.callVoid(self, "set_rotation", .{radians}); }

    pub fn setRotationDegrees(self: @This(), degrees: f64) !void { return support.callVoid(self, "set_rotation_degrees", .{degrees}); }

    pub fn setScale(self: @This(), scale: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_scale", 743155724, .{scale}); }

    pub fn setPivotOffset(self: @This(), pivot_offset: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_pivot_offset", 743155724, .{pivot_offset}); }

    pub fn setPivotOffsetRatio(self: @This(), ratio: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_pivot_offset_ratio", 743155724, .{ratio}); }

    pub fn getBegin(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_begin", 3341600327, .{}); }

    pub fn getEnd(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_end", 3341600327, .{}); }

    pub fn getPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_position", 3341600327, .{}); }

    pub fn getSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_size", 3341600327, .{}); }

    pub fn getRotation(self: @This()) !f64 { return support.call(self, f64, "get_rotation", .{}); }

    pub fn getRotationDegrees(self: @This()) !f64 { return support.call(self, f64, "get_rotation_degrees", .{}); }

    pub fn getScale(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_scale", 3341600327, .{}); }

    pub fn getPivotOffset(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_pivot_offset", 3341600327, .{}); }

    pub fn getPivotOffsetRatio(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_pivot_offset_ratio", 3341600327, .{}); }

    pub fn getCombinedPivotOffset(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_combined_pivot_offset", 3341600327, .{}); }

    pub fn getCustomMaximumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_custom_maximum_size", 3341600327, .{}); }

    pub fn getCustomMinimumSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_custom_minimum_size", 3341600327, .{}); }

    pub fn getParentAreaSize(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_parent_area_size", 3341600327, .{}); }

    pub fn getGlobalPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_global_position", 3341600327, .{}); }

    pub fn getScreenPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_screen_position", 3341600327, .{}); }

    pub fn setFocusMode(self: @This(), mode: Control.FocusMode) !void { return support.ptrcallMethodVoid(self, "Control", "set_focus_mode", 3232914922, .{mode}); }

    pub fn getFocusMode(self: @This()) !Control.FocusMode { return support.ptrcallMethod(self, Control.FocusMode, "Control", "get_focus_mode", 2132829277, .{}); }

    pub fn getFocusModeWithOverride(self: @This()) !Control.FocusMode { return support.ptrcallMethod(self, Control.FocusMode, "Control", "get_focus_mode_with_override", 2132829277, .{}); }

    pub fn setFocusBehaviorRecursive(self: @This(), focus_behavior_recursive: Control.FocusBehaviorRecursive) !void { return support.ptrcallMethodVoid(self, "Control", "set_focus_behavior_recursive", 4256832521, .{focus_behavior_recursive}); }

    pub fn getFocusBehaviorRecursive(self: @This()) !Control.FocusBehaviorRecursive { return support.ptrcallMethod(self, Control.FocusBehaviorRecursive, "Control", "get_focus_behavior_recursive", 2435707181, .{}); }

    pub fn hasFocus(self: @This(), ignore_hidden_focus: bool) !bool { return support.ptrcallMethod(self, bool, "Control", "has_focus", 3302206351, .{ignore_hidden_focus}); }

    pub fn grabFocus(self: @This(), hide_focus: bool) !void { return support.ptrcallMethodVoid(self, "Control", "grab_focus", 107499316, .{hide_focus}); }

    pub fn releaseFocus(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "release_focus", 3218959716, .{}); }

    pub fn findPrevValidFocus(self: @This()) !?Control { return support.call(self, ?Control, "find_prev_valid_focus", .{}); }

    pub fn findNextValidFocus(self: @This()) !?Control { return support.call(self, ?Control, "find_next_valid_focus", .{}); }

    pub fn findValidFocusNeighbor(self: @This(), side: Side) !?Control { return support.call(self, ?Control, "find_valid_focus_neighbor", .{side}); }

    pub fn setHSizeFlags(self: @This(), flags: Control.SizeFlags) !void { return support.ptrcallMethodVoid(self, "Control", "set_h_size_flags", 394851643, .{flags}); }

    pub fn getHSizeFlags(self: @This()) !Control.SizeFlags { return support.ptrcallMethod(self, Control.SizeFlags, "Control", "get_h_size_flags", 3781367401, .{}); }

    pub fn setStretchRatio(self: @This(), ratio: f64) !void { return support.callVoid(self, "set_stretch_ratio", .{ratio}); }

    pub fn getStretchRatio(self: @This()) !f64 { return support.call(self, f64, "get_stretch_ratio", .{}); }

    pub fn setVSizeFlags(self: @This(), flags: Control.SizeFlags) !void { return support.ptrcallMethodVoid(self, "Control", "set_v_size_flags", 394851643, .{flags}); }

    pub fn getVSizeFlags(self: @This()) !Control.SizeFlags { return support.ptrcallMethod(self, Control.SizeFlags, "Control", "get_v_size_flags", 3781367401, .{}); }

    pub fn setOffsetTransformEnabled(self: @This(), enabled: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_enabled", 2586408642, .{enabled}); }

    pub fn isOffsetTransformEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_offset_transform_enabled", 36873697, .{}); }

    pub fn setOffsetTransformPosition(self: @This(), offset: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_position", 743155724, .{offset}); }

    pub fn getOffsetTransformPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_offset_transform_position", 3341600327, .{}); }

    pub fn setOffsetTransformPositionRatio(self: @This(), offset: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_position_ratio", 743155724, .{offset}); }

    pub fn getOffsetTransformPositionRatio(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_offset_transform_position_ratio", 3341600327, .{}); }

    pub fn setOffsetTransformScale(self: @This(), scale: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_scale", 743155724, .{scale}); }

    pub fn getOffsetTransformScale(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_offset_transform_scale", 3341600327, .{}); }

    pub fn setOffsetTransformRotation(self: @This(), rotation: f64) !void { return support.callVoid(self, "set_offset_transform_rotation", .{rotation}); }

    pub fn getOffsetTransformRotation(self: @This()) !f64 { return support.call(self, f64, "get_offset_transform_rotation", .{}); }

    pub fn setOffsetTransformPivot(self: @This(), pivot: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_pivot", 743155724, .{pivot}); }

    pub fn getOffsetTransformPivot(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_offset_transform_pivot", 3341600327, .{}); }

    pub fn setOffsetTransformPivotRatio(self: @This(), pivot: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_pivot_ratio", 743155724, .{pivot}); }

    pub fn getOffsetTransformPivotRatio(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Control", "get_offset_transform_pivot_ratio", 3341600327, .{}); }

    pub fn setOffsetTransformVisualOnly(self: @This(), enabled: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_offset_transform_visual_only", 2586408642, .{enabled}); }

    pub fn isOffsetTransformVisualOnly(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_offset_transform_visual_only", 36873697, .{}); }

    pub fn setTheme(self: @This(), theme: ?Theme) !void { return support.callVoid(self, "set_theme", .{theme}); }

    pub fn getTheme(self: @This()) !?Theme { return support.call(self, ?Theme, "get_theme", .{}); }

    pub fn setThemeTypeVariation(self: @This(), theme_type: []const u8) !void { return support.callVoid(self, "set_theme_type_variation", .{theme_type}); }

    pub fn beginBulkThemeOverride(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "begin_bulk_theme_override", 3218959716, .{}); }

    pub fn endBulkThemeOverride(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "end_bulk_theme_override", 3218959716, .{}); }

    pub fn addThemeIconOverride(self: @This(), name: []const u8, texture: Texture2D) !void { return support.callVoid(self, "add_theme_icon_override", .{ name, texture }); }

    pub fn addThemeStyleboxOverride(self: @This(), name: []const u8, stylebox: StyleBox) !void { return support.callVoid(self, "add_theme_stylebox_override", .{ name, stylebox }); }

    pub fn addThemeFontOverride(self: @This(), name: []const u8, font: Font) !void { return support.callVoid(self, "add_theme_font_override", .{ name, font }); }

    pub fn addThemeFontSizeOverride(self: @This(), name: []const u8, font_size: i64) !void { return support.callVoid(self, "add_theme_font_size_override", .{ name, font_size }); }

    pub fn addThemeConstantOverride(self: @This(), name: []const u8, constant: i64) !void { return support.callVoid(self, "add_theme_constant_override", .{ name, constant }); }

    pub fn removeThemeIconOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_icon_override", .{name}); }

    pub fn removeThemeStyleboxOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_stylebox_override", .{name}); }

    pub fn removeThemeFontOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_font_override", .{name}); }

    pub fn removeThemeFontSizeOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_font_size_override", .{name}); }

    pub fn removeThemeColorOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_color_override", .{name}); }

    pub fn removeThemeConstantOverride(self: @This(), name: []const u8) !void { return support.callVoid(self, "remove_theme_constant_override", .{name}); }

    pub fn getThemeIcon(self: @This(), name: []const u8, theme_type: []const u8) !?Texture2D { return support.call(self, ?Texture2D, "get_theme_icon", .{ name, theme_type }); }

    pub fn getThemeStylebox(self: @This(), name: []const u8, theme_type: []const u8) !?StyleBox { return support.call(self, ?StyleBox, "get_theme_stylebox", .{ name, theme_type }); }

    pub fn getThemeFont(self: @This(), name: []const u8, theme_type: []const u8) !?Font { return support.call(self, ?Font, "get_theme_font", .{ name, theme_type }); }

    pub fn getThemeFontSize(self: @This(), name: []const u8, theme_type: []const u8) !i64 { return support.call(self, i64, "get_theme_font_size", .{ name, theme_type }); }

    pub fn getThemeConstant(self: @This(), name: []const u8, theme_type: []const u8) !i64 { return support.call(self, i64, "get_theme_constant", .{ name, theme_type }); }

    pub fn hasThemeIconOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_icon_override", .{name}); }

    pub fn hasThemeStyleboxOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_stylebox_override", .{name}); }

    pub fn hasThemeFontOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_font_override", .{name}); }

    pub fn hasThemeFontSizeOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_font_size_override", .{name}); }

    pub fn hasThemeColorOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_color_override", .{name}); }

    pub fn hasThemeConstantOverride(self: @This(), name: []const u8) !bool { return support.call(self, bool, "has_theme_constant_override", .{name}); }

    pub fn hasThemeIcon(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_icon", .{ name, theme_type }); }

    pub fn hasThemeStylebox(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_stylebox", .{ name, theme_type }); }

    pub fn hasThemeFont(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_font", .{ name, theme_type }); }

    pub fn hasThemeFontSize(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_font_size", .{ name, theme_type }); }

    pub fn hasThemeColor(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_color", .{ name, theme_type }); }

    pub fn hasThemeConstant(self: @This(), name: []const u8, theme_type: []const u8) !bool { return support.call(self, bool, "has_theme_constant", .{ name, theme_type }); }

    pub fn getThemeDefaultBaseScale(self: @This()) !f64 { return support.call(self, f64, "get_theme_default_base_scale", .{}); }

    pub fn getThemeDefaultFont(self: @This()) !?Font { return support.call(self, ?Font, "get_theme_default_font", .{}); }

    pub fn getThemeDefaultFontSize(self: @This()) !i64 { return support.call(self, i64, "get_theme_default_font_size", .{}); }

    pub fn getParentControl(self: @This()) !?Control { return support.call(self, ?Control, "get_parent_control", .{}); }

    pub fn setHGrowDirection(self: @This(), direction: Control.GrowDirection) !void { return support.ptrcallMethodVoid(self, "Control", "set_h_grow_direction", 2022385301, .{direction}); }

    pub fn getHGrowDirection(self: @This()) !Control.GrowDirection { return support.ptrcallMethod(self, Control.GrowDirection, "Control", "get_h_grow_direction", 3635610155, .{}); }

    pub fn setVGrowDirection(self: @This(), direction: Control.GrowDirection) !void { return support.ptrcallMethodVoid(self, "Control", "set_v_grow_direction", 2022385301, .{direction}); }

    pub fn getVGrowDirection(self: @This()) !Control.GrowDirection { return support.ptrcallMethod(self, Control.GrowDirection, "Control", "get_v_grow_direction", 3635610155, .{}); }

    pub fn setTooltipAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return support.ptrcallMethodVoid(self, "Control", "set_tooltip_auto_translate_mode", 776149714, .{mode}); }

    pub fn getTooltipAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return support.ptrcallMethod(self, Node.AutoTranslateMode, "Control", "get_tooltip_auto_translate_mode", 2498906432, .{}); }

    pub fn setTooltipText(self: @This(), hint: []const u8) !void { return support.callVoid(self, "set_tooltip_text", .{hint}); }

    pub fn setTranslationContext(self: @This(), context: []const u8) !void { return support.callVoid(self, "set_translation_context", .{context}); }

    pub fn setDefaultCursorShape(self: @This(), shape: Control.CursorShape) !void { return support.ptrcallMethodVoid(self, "Control", "set_default_cursor_shape", 217062046, .{shape}); }

    pub fn getDefaultCursorShape(self: @This()) !Control.CursorShape { return support.ptrcallMethod(self, Control.CursorShape, "Control", "get_default_cursor_shape", 2359535750, .{}); }

    pub fn getCursorShape(self: @This(), at_position: abi.Vector2(f64)) !Control.CursorShape { return support.ptrcallMethod(self, Control.CursorShape, "Control", "get_cursor_shape", 1395773853, .{at_position}); }

    pub fn setFocusNeighbor(self: @This(), side: Side, neighbor: []const u8) !void { return support.callVoid(self, "set_focus_neighbor", .{ side, neighbor }); }

    pub fn setFocusNext(self: @This(), next: []const u8) !void { return support.callVoid(self, "set_focus_next", .{next}); }

    pub fn setFocusPrevious(self: @This(), previous: []const u8) !void { return support.callVoid(self, "set_focus_previous", .{previous}); }

    pub fn accessibilityDrag(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "accessibility_drag", 3218959716, .{}); }

    pub fn accessibilityDrop(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "accessibility_drop", 3218959716, .{}); }

    pub fn setAccessibilityName(self: @This(), name: []const u8) !void { return support.callVoid(self, "set_accessibility_name", .{name}); }

    pub fn setAccessibilityDescription(self: @This(), description: []const u8) !void { return support.callVoid(self, "set_accessibility_description", .{description}); }

    pub fn setAccessibilityLive(self: @This(), mode: AccessibilityServer.AccessibilityLiveMode) !void { return support.ptrcallMethodVoid(self, "Control", "set_accessibility_live", 353443434, .{mode}); }

    pub fn getAccessibilityLive(self: @This()) !AccessibilityServer.AccessibilityLiveMode { return support.ptrcallMethod(self, AccessibilityServer.AccessibilityLiveMode, "Control", "get_accessibility_live", 2858591811, .{}); }

    pub fn setMouseFilter(self: @This(), filter: Control.MouseFilter) !void { return support.ptrcallMethodVoid(self, "Control", "set_mouse_filter", 3891156122, .{filter}); }

    pub fn getMouseFilter(self: @This()) !Control.MouseFilter { return support.ptrcallMethod(self, Control.MouseFilter, "Control", "get_mouse_filter", 1572545674, .{}); }

    pub fn getMouseFilterWithOverride(self: @This()) !Control.MouseFilter { return support.ptrcallMethod(self, Control.MouseFilter, "Control", "get_mouse_filter_with_override", 1572545674, .{}); }

    pub fn setMouseBehaviorRecursive(self: @This(), mouse_behavior_recursive: Control.MouseBehaviorRecursive) !void { return support.ptrcallMethodVoid(self, "Control", "set_mouse_behavior_recursive", 849284636, .{mouse_behavior_recursive}); }

    pub fn getMouseBehaviorRecursive(self: @This()) !Control.MouseBehaviorRecursive { return support.ptrcallMethod(self, Control.MouseBehaviorRecursive, "Control", "get_mouse_behavior_recursive", 3779367402, .{}); }

    pub fn setForcePassScrollEvents(self: @This(), force_pass_scroll_events: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_force_pass_scroll_events", 2586408642, .{force_pass_scroll_events}); }

    pub fn isForcePassScrollEvents(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_force_pass_scroll_events", 36873697, .{}); }

    pub fn setClipContents(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_clip_contents", 2586408642, .{enable}); }

    pub fn isClippingContents(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_clipping_contents", 2240911060, .{}); }

    pub fn grabClickFocus(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "grab_click_focus", 3218959716, .{}); }

    pub fn setDragPreview(self: @This(), control: ?Control) !void { return support.callVoid(self, "set_drag_preview", .{control}); }

    pub fn isDragSuccessful(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_drag_successful", 36873697, .{}); }

    pub fn warpMouse(self: @This(), position: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Control", "warp_mouse", 743155724, .{position}); }

    pub fn setShortcutContext(self: @This(), node: ?Node) !void { return support.callVoid(self, "set_shortcut_context", .{node}); }

    pub fn getShortcutContext(self: @This()) !?Node { return support.call(self, ?Node, "get_shortcut_context", .{}); }

    pub fn updateMaximumSize(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "update_maximum_size", 3218959716, .{}); }

    pub fn updateMinimumSize(self: @This()) !void { return support.ptrcallMethodVoid(self, "Control", "update_minimum_size", 3218959716, .{}); }

    pub fn setLayoutDirection(self: @This(), direction: Control.LayoutDirection) !void { return support.ptrcallMethodVoid(self, "Control", "set_layout_direction", 3310692370, .{direction}); }

    pub fn getLayoutDirection(self: @This()) !Control.LayoutDirection { return support.ptrcallMethod(self, Control.LayoutDirection, "Control", "get_layout_direction", 1546772008, .{}); }

    pub fn isLayoutRtl(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_layout_rtl", 36873697, .{}); }

    pub fn setAutoTranslate(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_auto_translate", 2586408642, .{enable}); }

    pub fn isAutoTranslating(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_auto_translating", 36873697, .{}); }

    pub fn setLocalizeNumeralSystem(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Control", "set_localize_numeral_system", 2586408642, .{enable}); }

    pub fn isLocalizingNumeralSystem(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Control", "is_localizing_numeral_system", 36873697, .{}); }

    pub inline fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void { return self.asNode().addSibling(sibling, force_readable_name); }

    pub inline fn setName(self: @This(), name: []const u8) !void { return self.asNode().setName(name); }

    pub inline fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void { return self.asNode().addChild(node, force_readable_name, internal); }

    pub inline fn removeChild(self: @This(), node: Node) !void { return self.asNode().removeChild(node); }

    pub inline fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void { return self.asNode().reparent(new_parent, keep_global_transform); }

    pub inline fn getChildCount(self: @This(), include_internal: bool) !i64 { return self.asNode().getChildCount(include_internal); }

    pub inline fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node { return self.asNode().getChild(idx, include_internal); }

    pub inline fn hasNode(self: @This(), path: []const u8) !bool { return self.asNode().hasNode(path); }

    pub inline fn getNode(self: @This(), path: []const u8) !?Node { return self.asNode().getNode(path); }

    pub inline fn getNodeOrNull(self: @This(), path: []const u8) !?Node { return self.asNode().getNodeOrNull(path); }

    pub inline fn getParent(self: @This()) !?Node { return self.asNode().getParent(); }

    pub inline fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node { return self.asNode().findChild(pattern, recursive, owned); }

    pub inline fn findParent(self: @This(), pattern: []const u8) !?Node { return self.asNode().findParent(pattern); }

    pub inline fn hasNodeAndResource(self: @This(), path: []const u8) !bool { return self.asNode().hasNodeAndResource(path); }

    pub inline fn isInsideTree(self: @This()) !bool { return self.asNode().isInsideTree(); }

    pub inline fn isPartOfEditedScene(self: @This()) !bool { return self.asNode().isPartOfEditedScene(); }

    pub inline fn isAncestorOf(self: @This(), node: Node) !bool { return self.asNode().isAncestorOf(node); }

    pub inline fn isGreaterThan(self: @This(), node: Node) !bool { return self.asNode().isGreaterThan(node); }

    pub inline fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void { return self.asNode().addToGroup(group, persistent); }

    pub inline fn removeFromGroup(self: @This(), group: []const u8) !void { return self.asNode().removeFromGroup(group); }

    pub inline fn isInGroup(self: @This(), group: []const u8) !bool { return self.asNode().isInGroup(group); }

    pub inline fn moveChild(self: @This(), child_node: Node, to_index: i64) !void { return self.asNode().moveChild(child_node, to_index); }

    pub inline fn setOwner(self: @This(), owner: ?Node) !void { return self.asNode().setOwner(owner); }

    pub inline fn getOwner(self: @This()) !?Node { return self.asNode().getOwner(); }

    pub inline fn getIndex(self: @This(), include_internal: bool) !i64 { return self.asNode().getIndex(include_internal); }

    pub inline fn printTree(self: @This()) !void { return self.asNode().printTree(); }

    pub inline fn printTreePretty(self: @This()) !void { return self.asNode().printTreePretty(); }

    pub inline fn setSceneFilePath(self: @This(), scene_file_path: []const u8) !void { return self.asNode().setSceneFilePath(scene_file_path); }

    pub inline fn propagateNotification(self: @This(), what: i64) !void { return self.asNode().propagateNotification(what); }

    pub inline fn setPhysicsProcess(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcess(enable); }

    pub inline fn getPhysicsProcessDeltaTime(self: @This()) !f64 { return self.asNode().getPhysicsProcessDeltaTime(); }

    pub inline fn isPhysicsProcessing(self: @This()) !bool { return self.asNode().isPhysicsProcessing(); }

    pub inline fn getProcessDeltaTime(self: @This()) !f64 { return self.asNode().getProcessDeltaTime(); }

    pub inline fn setProcess(self: @This(), enable: bool) !void { return self.asNode().setProcess(enable); }

    pub inline fn setProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setProcessPriority(priority); }

    pub inline fn getProcessPriority(self: @This()) !i64 { return self.asNode().getProcessPriority(); }

    pub inline fn setPhysicsProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setPhysicsProcessPriority(priority); }

    pub inline fn getPhysicsProcessPriority(self: @This()) !i64 { return self.asNode().getPhysicsProcessPriority(); }

    pub inline fn isProcessing(self: @This()) !bool { return self.asNode().isProcessing(); }

    pub inline fn setProcessInput(self: @This(), enable: bool) !void { return self.asNode().setProcessInput(enable); }

    pub inline fn isProcessingInput(self: @This()) !bool { return self.asNode().isProcessingInput(); }

    pub inline fn setProcessShortcutInput(self: @This(), enable: bool) !void { return self.asNode().setProcessShortcutInput(enable); }

    pub inline fn isProcessingShortcutInput(self: @This()) !bool { return self.asNode().isProcessingShortcutInput(); }

    pub inline fn setProcessUnhandledInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledInput(enable); }

    pub inline fn isProcessingUnhandledInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledInput(); }

    pub inline fn setProcessUnhandledKeyInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledKeyInput(enable); }

    pub inline fn isProcessingUnhandledKeyInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledKeyInput(); }

    pub inline fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void { return self.asNode().setProcessMode(mode); }

    pub inline fn getProcessMode(self: @This()) !Node.ProcessMode { return self.asNode().getProcessMode(); }

    pub inline fn canProcess(self: @This()) !bool { return self.asNode().canProcess(); }

    pub inline fn setProcessThreadGroup(self: @This(), mode: Node.ProcessThreadGroup) !void { return self.asNode().setProcessThreadGroup(mode); }

    pub inline fn getProcessThreadGroup(self: @This()) !Node.ProcessThreadGroup { return self.asNode().getProcessThreadGroup(); }

    pub inline fn setProcessThreadMessages(self: @This(), flags: Node.ProcessThreadMessages) !void { return self.asNode().setProcessThreadMessages(flags); }

    pub inline fn getProcessThreadMessages(self: @This()) !Node.ProcessThreadMessages { return self.asNode().getProcessThreadMessages(); }

    pub inline fn setProcessThreadGroupOrder(self: @This(), order: i64) !void { return self.asNode().setProcessThreadGroupOrder(order); }

    pub inline fn getProcessThreadGroupOrder(self: @This()) !i64 { return self.asNode().getProcessThreadGroupOrder(); }

    pub inline fn queueAccessibilityUpdate(self: @This()) !void { return self.asNode().queueAccessibilityUpdate(); }

    pub inline fn setDisplayFolded(self: @This(), fold: bool) !void { return self.asNode().setDisplayFolded(fold); }

    pub inline fn isDisplayedFolded(self: @This()) !bool { return self.asNode().isDisplayedFolded(); }

    pub inline fn setProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setProcessInternal(enable); }

    pub inline fn isProcessingInternal(self: @This()) !bool { return self.asNode().isProcessingInternal(); }

    pub inline fn setPhysicsProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcessInternal(enable); }

    pub inline fn isPhysicsProcessingInternal(self: @This()) !bool { return self.asNode().isPhysicsProcessingInternal(); }

    pub inline fn setPhysicsInterpolationMode(self: @This(), mode: Node.PhysicsInterpolationMode) !void { return self.asNode().setPhysicsInterpolationMode(mode); }

    pub inline fn getPhysicsInterpolationMode(self: @This()) !Node.PhysicsInterpolationMode { return self.asNode().getPhysicsInterpolationMode(); }

    pub inline fn isPhysicsInterpolated(self: @This()) !bool { return self.asNode().isPhysicsInterpolated(); }

    pub inline fn isPhysicsInterpolatedAndEnabled(self: @This()) !bool { return self.asNode().isPhysicsInterpolatedAndEnabled(); }

    pub inline fn resetPhysicsInterpolation(self: @This()) !void { return self.asNode().resetPhysicsInterpolation(); }

    pub inline fn setAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return self.asNode().setAutoTranslateMode(mode); }

    pub inline fn getAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return self.asNode().getAutoTranslateMode(); }

    pub inline fn canAutoTranslate(self: @This()) !bool { return self.asNode().canAutoTranslate(); }

    pub inline fn setTranslationDomainInherited(self: @This()) !void { return self.asNode().setTranslationDomainInherited(); }

    pub inline fn getWindow(self: @This()) !?Window { return self.asNode().getWindow(); }

    pub inline fn getLastExclusiveWindow(self: @This()) !?Window { return self.asNode().getLastExclusiveWindow(); }

    pub inline fn getTree(self: @This()) !?SceneTree { return self.asNode().getTree(); }

    pub inline fn createTween(self: @This()) !Tween { return self.asNode().createTween(); }

    pub inline fn duplicate(self: @This(), flags: i64) !?Node { return self.asNode().duplicate(flags); }

    pub inline fn replaceBy(self: @This(), node: Node, keep_groups: bool) !void { return self.asNode().replaceBy(node, keep_groups); }

    pub inline fn setSceneInstanceLoadPlaceholder(self: @This(), load_placeholder: bool) !void { return self.asNode().setSceneInstanceLoadPlaceholder(load_placeholder); }

    pub inline fn getSceneInstanceLoadPlaceholder(self: @This()) !bool { return self.asNode().getSceneInstanceLoadPlaceholder(); }

    pub inline fn setEditableInstance(self: @This(), node: Node, is_editable: bool) !void { return self.asNode().setEditableInstance(node, is_editable); }

    pub inline fn isEditableInstance(self: @This(), node: ?Node) !bool { return self.asNode().isEditableInstance(node); }

    pub inline fn getViewport(self: @This()) !?Viewport { return self.asNode().getViewport(); }

    pub inline fn queueFree(self: @This()) !void { return self.asNode().queueFree(); }

    pub inline fn requestReady(self: @This()) !void { return self.asNode().requestReady(); }

    pub inline fn isNodeReady(self: @This()) !bool { return self.asNode().isNodeReady(); }

    pub inline fn setMultiplayerAuthority(self: @This(), id: i64, recursive: bool) !void { return self.asNode().setMultiplayerAuthority(id, recursive); }

    pub inline fn getMultiplayerAuthority(self: @This()) !i64 { return self.asNode().getMultiplayerAuthority(); }

    pub inline fn isMultiplayerAuthority(self: @This()) !bool { return self.asNode().isMultiplayerAuthority(); }

    pub inline fn getMultiplayer(self: @This()) !?MultiplayerAPI { return self.asNode().getMultiplayer(); }

    pub inline fn setEditorDescription(self: @This(), editor_description: []const u8) !void { return self.asNode().setEditorDescription(editor_description); }

    pub inline fn setUniqueNameInOwner(self: @This(), enable: bool) !void { return self.asNode().setUniqueNameInOwner(enable); }

    pub inline fn isUniqueNameInOwner(self: @This()) !bool { return self.asNode().isUniqueNameInOwner(); }

    pub inline fn updateConfigurationWarnings(self: @This()) !void { return self.asNode().updateConfigurationWarnings(); }

    pub inline fn notifyDeferredThreadGroup(self: @This(), what: i64) !void { return self.asNode().notifyDeferredThreadGroup(what); }

    pub inline fn notifyThreadSafe(self: @This(), what: i64) !void { return self.asNode().notifyThreadSafe(what); }

    pub inline fn setVisible(self: @This(), visible: bool) !void { return self.asCanvasItem().setVisible(visible); }

    pub inline fn isVisible(self: @This()) !bool { return self.asCanvasItem().isVisible(); }

    pub inline fn isVisibleInTree(self: @This()) !bool { return self.asCanvasItem().isVisibleInTree(); }

    pub inline fn show(self: @This()) !void { return self.asCanvasItem().show(); }

    pub inline fn hide(self: @This()) !void { return self.asCanvasItem().hide(); }

    pub inline fn queueRedraw(self: @This()) !void { return self.asCanvasItem().queueRedraw(); }

    pub inline fn moveToFront(self: @This()) !void { return self.asCanvasItem().moveToFront(); }

    pub inline fn setAsTopLevel(self: @This(), enable: bool) !void { return self.asCanvasItem().setAsTopLevel(enable); }

    pub inline fn isSetAsTopLevel(self: @This()) !bool { return self.asCanvasItem().isSetAsTopLevel(); }

    pub inline fn setLightMask(self: @This(), light_mask: i64) !void { return self.asCanvasItem().setLightMask(light_mask); }

    pub inline fn getLightMask(self: @This()) !i64 { return self.asCanvasItem().getLightMask(); }

    pub inline fn setZIndex(self: @This(), z_index: i64) !void { return self.asCanvasItem().setZIndex(z_index); }

    pub inline fn getZIndex(self: @This()) !i64 { return self.asCanvasItem().getZIndex(); }

    pub inline fn setZAsRelative(self: @This(), enable: bool) !void { return self.asCanvasItem().setZAsRelative(enable); }

    pub inline fn isZRelative(self: @This()) !bool { return self.asCanvasItem().isZRelative(); }

    pub inline fn setYSortEnabled(self: @This(), enabled: bool) !void { return self.asCanvasItem().setYSortEnabled(enabled); }

    pub inline fn isYSortEnabled(self: @This()) !bool { return self.asCanvasItem().isYSortEnabled(); }

    pub inline fn setDrawBehindParent(self: @This(), enable: bool) !void { return self.asCanvasItem().setDrawBehindParent(enable); }

    pub inline fn isDrawBehindParentEnabled(self: @This()) !bool { return self.asCanvasItem().isDrawBehindParentEnabled(); }

    pub inline fn drawMultimesh(self: @This(), multimesh: MultiMesh, texture: ?Texture2D) !void { return self.asCanvasItem().drawMultimesh(multimesh, texture); }

    pub inline fn drawSetTransform(self: @This(), position: abi.Vector2(f64), rotation: f64, scale: abi.Vector2(f64)) !void { return self.asCanvasItem().drawSetTransform(position, rotation, scale); }

    pub inline fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void { return self.asCanvasItem().drawAnimationSlice(animation_length, slice_begin, slice_end, offset); }

    pub inline fn drawEndAnimation(self: @This()) !void { return self.asCanvasItem().drawEndAnimation(); }

    pub inline fn getLocalMousePosition(self: @This()) !abi.Vector2(f64) { return self.asCanvasItem().getLocalMousePosition(); }

    pub inline fn getGlobalMousePosition(self: @This()) !abi.Vector2(f64) { return self.asCanvasItem().getGlobalMousePosition(); }

    pub inline fn getCanvasLayerNode(self: @This()) !?CanvasLayer { return self.asCanvasItem().getCanvasLayerNode(); }

    pub inline fn getWorld2D(self: @This()) !?World2D { return self.asCanvasItem().getWorld2D(); }

    pub inline fn setMaterial(self: @This(), material: ?Material) !void { return self.asCanvasItem().setMaterial(material); }

    pub inline fn getMaterial(self: @This()) !?Material { return self.asCanvasItem().getMaterial(); }

    pub inline fn setUseParentMaterial(self: @This(), enable: bool) !void { return self.asCanvasItem().setUseParentMaterial(enable); }

    pub inline fn getUseParentMaterial(self: @This()) !bool { return self.asCanvasItem().getUseParentMaterial(); }

    pub inline fn setNotifyLocalTransform(self: @This(), enable: bool) !void { return self.asCanvasItem().setNotifyLocalTransform(enable); }

    pub inline fn isLocalTransformNotificationEnabled(self: @This()) !bool { return self.asCanvasItem().isLocalTransformNotificationEnabled(); }

    pub inline fn setNotifyTransform(self: @This(), enable: bool) !void { return self.asCanvasItem().setNotifyTransform(enable); }

    pub inline fn isTransformNotificationEnabled(self: @This()) !bool { return self.asCanvasItem().isTransformNotificationEnabled(); }

    pub inline fn forceUpdateTransform(self: @This()) !void { return self.asCanvasItem().forceUpdateTransform(); }

    pub inline fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2(f64)) !abi.Vector2(f64) { return self.asCanvasItem().makeCanvasPositionLocal(viewport_point); }

    pub inline fn makeInputLocal(self: @This(), event: InputEvent) !InputEvent { return self.asCanvasItem().makeInputLocal(event); }

    pub inline fn setVisibilityLayer(self: @This(), layer: i64) !void { return self.asCanvasItem().setVisibilityLayer(layer); }

    pub inline fn getVisibilityLayer(self: @This()) !i64 { return self.asCanvasItem().getVisibilityLayer(); }

    pub inline fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void { return self.asCanvasItem().setVisibilityLayerBit(layer, enabled); }

    pub inline fn getVisibilityLayerBit(self: @This(), layer: i64) !bool { return self.asCanvasItem().getVisibilityLayerBit(layer); }

    pub inline fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void { return self.asCanvasItem().setTextureFilter(mode); }

    pub inline fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter { return self.asCanvasItem().getTextureFilter(); }

    pub inline fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void { return self.asCanvasItem().setTextureRepeat(mode); }

    pub inline fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat { return self.asCanvasItem().getTextureRepeat(); }

    pub inline fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void { return self.asCanvasItem().setClipChildrenMode(mode); }

    pub inline fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode { return self.asCanvasItem().getClipChildrenMode(); }

    pub inline fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void { return self.asCanvasItem().setOversamplingWithScale(enabled); }

    pub inline fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale { return self.asCanvasItem().getOversamplingWithScale(); }
};
