// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const InputEvent = extern struct {
    owner: u64,

    pub const godot_class = "InputEvent";
    pub const emitSignal = support.emitSignal;
};
