// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");
const EulerOrder = @import("../global_enums.zig").EulerOrder;
const Node = @import("node.zig").Node;
const Window = @import("window.zig").Window;
const SceneTree = @import("scene_tree.zig").SceneTree;
const Tween = @import("tween.zig").Tween;
const Viewport = @import("viewport.zig").Viewport;
const MultiplayerAPI = @import("multiplayer_api.zig").MultiplayerAPI;
const World3D = @import("world_3d.zig").World3D;
const Node3DGizmo = @import("node_3d_gizmo.zig").Node3DGizmo;

pub const Node3D = extern struct {
    owner: u64,

    pub const godot_class = "Node3D";
    pub const emitSignal = support.emitSignal;

    pub const RotationEditMode = enum(i64) {
        euler = 0,
        quaternion = 1,
        basis = 2,
    };

    pub fn asNode(self: @This()) Node { return .{ .owner = self.owner }; }

    pub fn setRotationOrder(self: @This(), order: EulerOrder) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_rotation_order", 1820889989, .{order}); }

    pub fn getRotationOrder(self: @This()) !EulerOrder { return support.ptrcallMethod(self, EulerOrder, "Node3D", "get_rotation_order", 916939469, .{}); }

    pub fn setRotationEditMode(self: @This(), edit_mode: Node3D.RotationEditMode) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_rotation_edit_mode", 141483330, .{edit_mode}); }

    pub fn getRotationEditMode(self: @This()) !Node3D.RotationEditMode { return support.ptrcallMethod(self, Node3D.RotationEditMode, "Node3D", "get_rotation_edit_mode", 1572188370, .{}); }

    pub fn getParentNode3D(self: @This()) !?Node3D { return support.call(self, ?Node3D, "get_parent_node_3d", .{}); }

    pub fn setIgnoreTransformNotification(self: @This(), enabled: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_ignore_transform_notification", 2586408642, .{enabled}); }

    pub fn setAsTopLevel(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_as_top_level", 2586408642, .{enable}); }

    pub fn isSetAsTopLevel(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_set_as_top_level", 36873697, .{}); }

    pub fn setDisableScale(self: @This(), disable: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_disable_scale", 2586408642, .{disable}); }

    pub fn isScaleDisabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_scale_disabled", 36873697, .{}); }

    pub fn getWorld3D(self: @This()) !?World3D { return support.call(self, ?World3D, "get_world_3d", .{}); }

    pub fn forceUpdateTransform(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "force_update_transform", 3218959716, .{}); }

    pub fn setVisibilityParent(self: @This(), path: []const u8) !void { return support.callVoid(self, "set_visibility_parent", .{path}); }

    pub fn updateGizmos(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "update_gizmos", 3218959716, .{}); }

    pub fn addGizmo(self: @This(), gizmo: ?Node3DGizmo) !void { return support.callVoid(self, "add_gizmo", .{gizmo}); }

    pub fn clearGizmos(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "clear_gizmos", 3218959716, .{}); }

    pub fn clearSubgizmoSelection(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "clear_subgizmo_selection", 3218959716, .{}); }

    pub fn setVisible(self: @This(), visible: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_visible", 2586408642, .{visible}); }

    pub fn isVisible(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_visible", 36873697, .{}); }

    pub fn isVisibleInTree(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_visible_in_tree", 36873697, .{}); }

    pub fn show(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "show", 3218959716, .{}); }

    pub fn hide(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "hide", 3218959716, .{}); }

    pub fn setNotifyLocalTransform(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_notify_local_transform", 2586408642, .{enable}); }

    pub fn isLocalTransformNotificationEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_local_transform_notification_enabled", 36873697, .{}); }

    pub fn setNotifyTransform(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_notify_transform", 2586408642, .{enable}); }

    pub fn isTransformNotificationEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node3D", "is_transform_notification_enabled", 36873697, .{}); }

    pub fn rotateX(self: @This(), angle: f64) !void { return support.callVoid(self, "rotate_x", .{angle}); }

    pub fn rotateY(self: @This(), angle: f64) !void { return support.callVoid(self, "rotate_y", .{angle}); }

    pub fn rotateZ(self: @This(), angle: f64) !void { return support.callVoid(self, "rotate_z", .{angle}); }

    pub fn orthonormalize(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "orthonormalize", 3218959716, .{}); }

    pub fn setIdentity(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node3D", "set_identity", 3218959716, .{}); }

    pub inline fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void { return self.asNode().addSibling(sibling, force_readable_name); }

    pub inline fn setName(self: @This(), name: []const u8) !void { return self.asNode().setName(name); }

    pub inline fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void { return self.asNode().addChild(node, force_readable_name, internal); }

    pub inline fn removeChild(self: @This(), node: Node) !void { return self.asNode().removeChild(node); }

    pub inline fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void { return self.asNode().reparent(new_parent, keep_global_transform); }

    pub inline fn getChildCount(self: @This(), include_internal: bool) !i64 { return self.asNode().getChildCount(include_internal); }

    pub inline fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node { return self.asNode().getChild(idx, include_internal); }

    pub inline fn hasNode(self: @This(), path: []const u8) !bool { return self.asNode().hasNode(path); }

    pub inline fn getNode(self: @This(), path: []const u8) !?Node { return self.asNode().getNode(path); }

    pub inline fn getNodeOrNull(self: @This(), path: []const u8) !?Node { return self.asNode().getNodeOrNull(path); }

    pub inline fn getParent(self: @This()) !?Node { return self.asNode().getParent(); }

    pub inline fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node { return self.asNode().findChild(pattern, recursive, owned); }

    pub inline fn findParent(self: @This(), pattern: []const u8) !?Node { return self.asNode().findParent(pattern); }

    pub inline fn hasNodeAndResource(self: @This(), path: []const u8) !bool { return self.asNode().hasNodeAndResource(path); }

    pub inline fn isInsideTree(self: @This()) !bool { return self.asNode().isInsideTree(); }

    pub inline fn isPartOfEditedScene(self: @This()) !bool { return self.asNode().isPartOfEditedScene(); }

    pub inline fn isAncestorOf(self: @This(), node: Node) !bool { return self.asNode().isAncestorOf(node); }

    pub inline fn isGreaterThan(self: @This(), node: Node) !bool { return self.asNode().isGreaterThan(node); }

    pub inline fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void { return self.asNode().addToGroup(group, persistent); }

    pub inline fn removeFromGroup(self: @This(), group: []const u8) !void { return self.asNode().removeFromGroup(group); }

    pub inline fn isInGroup(self: @This(), group: []const u8) !bool { return self.asNode().isInGroup(group); }

    pub inline fn moveChild(self: @This(), child_node: Node, to_index: i64) !void { return self.asNode().moveChild(child_node, to_index); }

    pub inline fn setOwner(self: @This(), owner: ?Node) !void { return self.asNode().setOwner(owner); }

    pub inline fn getOwner(self: @This()) !?Node { return self.asNode().getOwner(); }

    pub inline fn getIndex(self: @This(), include_internal: bool) !i64 { return self.asNode().getIndex(include_internal); }

    pub inline fn printTree(self: @This()) !void { return self.asNode().printTree(); }

    pub inline fn printTreePretty(self: @This()) !void { return self.asNode().printTreePretty(); }

    pub inline fn setSceneFilePath(self: @This(), scene_file_path: []const u8) !void { return self.asNode().setSceneFilePath(scene_file_path); }

    pub inline fn propagateNotification(self: @This(), what: i64) !void { return self.asNode().propagateNotification(what); }

    pub inline fn setPhysicsProcess(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcess(enable); }

    pub inline fn getPhysicsProcessDeltaTime(self: @This()) !f64 { return self.asNode().getPhysicsProcessDeltaTime(); }

    pub inline fn isPhysicsProcessing(self: @This()) !bool { return self.asNode().isPhysicsProcessing(); }

    pub inline fn getProcessDeltaTime(self: @This()) !f64 { return self.asNode().getProcessDeltaTime(); }

    pub inline fn setProcess(self: @This(), enable: bool) !void { return self.asNode().setProcess(enable); }

    pub inline fn setProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setProcessPriority(priority); }

    pub inline fn getProcessPriority(self: @This()) !i64 { return self.asNode().getProcessPriority(); }

    pub inline fn setPhysicsProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setPhysicsProcessPriority(priority); }

    pub inline fn getPhysicsProcessPriority(self: @This()) !i64 { return self.asNode().getPhysicsProcessPriority(); }

    pub inline fn isProcessing(self: @This()) !bool { return self.asNode().isProcessing(); }

    pub inline fn setProcessInput(self: @This(), enable: bool) !void { return self.asNode().setProcessInput(enable); }

    pub inline fn isProcessingInput(self: @This()) !bool { return self.asNode().isProcessingInput(); }

    pub inline fn setProcessShortcutInput(self: @This(), enable: bool) !void { return self.asNode().setProcessShortcutInput(enable); }

    pub inline fn isProcessingShortcutInput(self: @This()) !bool { return self.asNode().isProcessingShortcutInput(); }

    pub inline fn setProcessUnhandledInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledInput(enable); }

    pub inline fn isProcessingUnhandledInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledInput(); }

    pub inline fn setProcessUnhandledKeyInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledKeyInput(enable); }

    pub inline fn isProcessingUnhandledKeyInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledKeyInput(); }

    pub inline fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void { return self.asNode().setProcessMode(mode); }

    pub inline fn getProcessMode(self: @This()) !Node.ProcessMode { return self.asNode().getProcessMode(); }

    pub inline fn canProcess(self: @This()) !bool { return self.asNode().canProcess(); }

    pub inline fn setProcessThreadGroup(self: @This(), mode: Node.ProcessThreadGroup) !void { return self.asNode().setProcessThreadGroup(mode); }

    pub inline fn getProcessThreadGroup(self: @This()) !Node.ProcessThreadGroup { return self.asNode().getProcessThreadGroup(); }

    pub inline fn setProcessThreadMessages(self: @This(), flags: Node.ProcessThreadMessages) !void { return self.asNode().setProcessThreadMessages(flags); }

    pub inline fn getProcessThreadMessages(self: @This()) !Node.ProcessThreadMessages { return self.asNode().getProcessThreadMessages(); }

    pub inline fn setProcessThreadGroupOrder(self: @This(), order: i64) !void { return self.asNode().setProcessThreadGroupOrder(order); }

    pub inline fn getProcessThreadGroupOrder(self: @This()) !i64 { return self.asNode().getProcessThreadGroupOrder(); }

    pub inline fn queueAccessibilityUpdate(self: @This()) !void { return self.asNode().queueAccessibilityUpdate(); }

    pub inline fn setDisplayFolded(self: @This(), fold: bool) !void { return self.asNode().setDisplayFolded(fold); }

    pub inline fn isDisplayedFolded(self: @This()) !bool { return self.asNode().isDisplayedFolded(); }

    pub inline fn setProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setProcessInternal(enable); }

    pub inline fn isProcessingInternal(self: @This()) !bool { return self.asNode().isProcessingInternal(); }

    pub inline fn setPhysicsProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcessInternal(enable); }

    pub inline fn isPhysicsProcessingInternal(self: @This()) !bool { return self.asNode().isPhysicsProcessingInternal(); }

    pub inline fn setPhysicsInterpolationMode(self: @This(), mode: Node.PhysicsInterpolationMode) !void { return self.asNode().setPhysicsInterpolationMode(mode); }

    pub inline fn getPhysicsInterpolationMode(self: @This()) !Node.PhysicsInterpolationMode { return self.asNode().getPhysicsInterpolationMode(); }

    pub inline fn isPhysicsInterpolated(self: @This()) !bool { return self.asNode().isPhysicsInterpolated(); }

    pub inline fn isPhysicsInterpolatedAndEnabled(self: @This()) !bool { return self.asNode().isPhysicsInterpolatedAndEnabled(); }

    pub inline fn resetPhysicsInterpolation(self: @This()) !void { return self.asNode().resetPhysicsInterpolation(); }

    pub inline fn setAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return self.asNode().setAutoTranslateMode(mode); }

    pub inline fn getAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return self.asNode().getAutoTranslateMode(); }

    pub inline fn canAutoTranslate(self: @This()) !bool { return self.asNode().canAutoTranslate(); }

    pub inline fn setTranslationDomainInherited(self: @This()) !void { return self.asNode().setTranslationDomainInherited(); }

    pub inline fn getWindow(self: @This()) !?Window { return self.asNode().getWindow(); }

    pub inline fn getLastExclusiveWindow(self: @This()) !?Window { return self.asNode().getLastExclusiveWindow(); }

    pub inline fn getTree(self: @This()) !?SceneTree { return self.asNode().getTree(); }

    pub inline fn createTween(self: @This()) !Tween { return self.asNode().createTween(); }

    pub inline fn duplicate(self: @This(), flags: i64) !?Node { return self.asNode().duplicate(flags); }

    pub inline fn replaceBy(self: @This(), node: Node, keep_groups: bool) !void { return self.asNode().replaceBy(node, keep_groups); }

    pub inline fn setSceneInstanceLoadPlaceholder(self: @This(), load_placeholder: bool) !void { return self.asNode().setSceneInstanceLoadPlaceholder(load_placeholder); }

    pub inline fn getSceneInstanceLoadPlaceholder(self: @This()) !bool { return self.asNode().getSceneInstanceLoadPlaceholder(); }

    pub inline fn setEditableInstance(self: @This(), node: Node, is_editable: bool) !void { return self.asNode().setEditableInstance(node, is_editable); }

    pub inline fn isEditableInstance(self: @This(), node: ?Node) !bool { return self.asNode().isEditableInstance(node); }

    pub inline fn getViewport(self: @This()) !?Viewport { return self.asNode().getViewport(); }

    pub inline fn queueFree(self: @This()) !void { return self.asNode().queueFree(); }

    pub inline fn requestReady(self: @This()) !void { return self.asNode().requestReady(); }

    pub inline fn isNodeReady(self: @This()) !bool { return self.asNode().isNodeReady(); }

    pub inline fn setMultiplayerAuthority(self: @This(), id: i64, recursive: bool) !void { return self.asNode().setMultiplayerAuthority(id, recursive); }

    pub inline fn getMultiplayerAuthority(self: @This()) !i64 { return self.asNode().getMultiplayerAuthority(); }

    pub inline fn isMultiplayerAuthority(self: @This()) !bool { return self.asNode().isMultiplayerAuthority(); }

    pub inline fn getMultiplayer(self: @This()) !?MultiplayerAPI { return self.asNode().getMultiplayer(); }

    pub inline fn setEditorDescription(self: @This(), editor_description: []const u8) !void { return self.asNode().setEditorDescription(editor_description); }

    pub inline fn setUniqueNameInOwner(self: @This(), enable: bool) !void { return self.asNode().setUniqueNameInOwner(enable); }

    pub inline fn isUniqueNameInOwner(self: @This()) !bool { return self.asNode().isUniqueNameInOwner(); }

    pub inline fn updateConfigurationWarnings(self: @This()) !void { return self.asNode().updateConfigurationWarnings(); }

    pub inline fn notifyDeferredThreadGroup(self: @This(), what: i64) !void { return self.asNode().notifyDeferredThreadGroup(what); }

    pub inline fn notifyThreadSafe(self: @This(), what: i64) !void { return self.asNode().notifyThreadSafe(what); }
};
