// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");
const Window = @import("window.zig").Window;
const SceneTree = @import("scene_tree.zig").SceneTree;
const Tween = @import("tween.zig").Tween;
const Viewport = @import("viewport.zig").Viewport;
const MultiplayerAPI = @import("multiplayer_api.zig").MultiplayerAPI;

pub const Node = extern struct {
    owner: u64,

    pub const godot_class = "Node";
    pub const emitSignal = support.emitSignal;

    pub const InternalMode = enum(i64) {
        disabled = 0,
        front = 1,
        back = 2,
    };

    pub const ProcessMode = enum(i64) {
        inherit = 0,
        pausable = 1,
        when_paused = 2,
        always = 3,
        disabled = 4,
    };

    pub const ProcessThreadGroup = enum(i64) {
        inherit = 0,
        main_thread = 1,
        sub_thread = 2,
    };

    pub const ProcessThreadMessages = enum(i64) {
        flag_process_thread_messages = 1,
        flag_process_thread_messages_physics = 2,
        flag_process_thread_messages_all = 3,
        _,
    };

    pub const PhysicsInterpolationMode = enum(i64) {
        inherit = 0,
        on = 1,
        off = 2,
    };

    pub const AutoTranslateMode = enum(i64) {
        inherit = 0,
        always = 1,
        disabled = 2,
    };

    pub fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void { return support.callVoid(self, "add_sibling", .{ sibling, force_readable_name }); }

    pub fn setName(self: @This(), name: []const u8) !void { return support.callVoid(self, "set_name", .{name}); }

    pub fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void { return support.callVoid(self, "add_child", .{ node, force_readable_name, internal }); }

    pub fn removeChild(self: @This(), node: Node) !void { return support.callVoid(self, "remove_child", .{node}); }

    pub fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void { return support.callVoid(self, "reparent", .{ new_parent, keep_global_transform }); }

    pub fn getChildCount(self: @This(), include_internal: bool) !i64 { return support.call(self, i64, "get_child_count", .{include_internal}); }

    pub fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node { return support.call(self, ?Node, "get_child", .{ idx, include_internal }); }

    pub fn hasNode(self: @This(), path: []const u8) !bool { return support.call(self, bool, "has_node", .{path}); }

    pub fn getNode(self: @This(), path: []const u8) !?Node { return support.call(self, ?Node, "get_node", .{path}); }

    pub fn getNodeOrNull(self: @This(), path: []const u8) !?Node { return support.call(self, ?Node, "get_node_or_null", .{path}); }

    pub fn getParent(self: @This()) !?Node { return support.call(self, ?Node, "get_parent", .{}); }

    pub fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node { return support.call(self, ?Node, "find_child", .{ pattern, recursive, owned }); }

    pub fn findParent(self: @This(), pattern: []const u8) !?Node { return support.call(self, ?Node, "find_parent", .{pattern}); }

    pub fn hasNodeAndResource(self: @This(), path: []const u8) !bool { return support.call(self, bool, "has_node_and_resource", .{path}); }

    pub fn isInsideTree(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_inside_tree", 36873697, .{}); }

    pub fn isPartOfEditedScene(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_part_of_edited_scene", 36873697, .{}); }

    pub fn isAncestorOf(self: @This(), node: Node) !bool { return support.call(self, bool, "is_ancestor_of", .{node}); }

    pub fn isGreaterThan(self: @This(), node: Node) !bool { return support.call(self, bool, "is_greater_than", .{node}); }

    pub fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void { return support.callVoid(self, "add_to_group", .{ group, persistent }); }

    pub fn removeFromGroup(self: @This(), group: []const u8) !void { return support.callVoid(self, "remove_from_group", .{group}); }

    pub fn isInGroup(self: @This(), group: []const u8) !bool { return support.call(self, bool, "is_in_group", .{group}); }

    pub fn moveChild(self: @This(), child_node: Node, to_index: i64) !void { return support.callVoid(self, "move_child", .{ child_node, to_index }); }

    pub fn setOwner(self: @This(), owner: ?Node) !void { return support.callVoid(self, "set_owner", .{owner}); }

    pub fn getOwner(self: @This()) !?Node { return support.call(self, ?Node, "get_owner", .{}); }

    pub fn getIndex(self: @This(), include_internal: bool) !i64 { return support.call(self, i64, "get_index", .{include_internal}); }

    pub fn printTree(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "print_tree", 3218959716, .{}); }

    pub fn printTreePretty(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "print_tree_pretty", 3218959716, .{}); }

    pub fn setSceneFilePath(self: @This(), scene_file_path: []const u8) !void { return support.callVoid(self, "set_scene_file_path", .{scene_file_path}); }

    pub fn propagateNotification(self: @This(), what: i64) !void { return support.callVoid(self, "propagate_notification", .{what}); }

    pub fn setPhysicsProcess(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_physics_process", 2586408642, .{enable}); }

    pub fn getPhysicsProcessDeltaTime(self: @This()) !f64 { return support.ptrcallMethod(self, f64, "Node", "get_physics_process_delta_time", 1740695150, .{}); }

    pub fn isPhysicsProcessing(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_physics_processing", 36873697, .{}); }

    pub fn getProcessDeltaTime(self: @This()) !f64 { return support.ptrcallMethod(self, f64, "Node", "get_process_delta_time", 1740695150, .{}); }

    pub fn setProcess(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process", 2586408642, .{enable}); }

    pub fn setProcessPriority(self: @This(), priority: i64) !void { return support.callVoid(self, "set_process_priority", .{priority}); }

    pub fn getProcessPriority(self: @This()) !i64 { return support.call(self, i64, "get_process_priority", .{}); }

    pub fn setPhysicsProcessPriority(self: @This(), priority: i64) !void { return support.callVoid(self, "set_physics_process_priority", .{priority}); }

    pub fn getPhysicsProcessPriority(self: @This()) !i64 { return support.call(self, i64, "get_physics_process_priority", .{}); }

    pub fn isProcessing(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing", 36873697, .{}); }

    pub fn setProcessInput(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_input", 2586408642, .{enable}); }

    pub fn isProcessingInput(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing_input", 36873697, .{}); }

    pub fn setProcessShortcutInput(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_shortcut_input", 2586408642, .{enable}); }

    pub fn isProcessingShortcutInput(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing_shortcut_input", 36873697, .{}); }

    pub fn setProcessUnhandledInput(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_unhandled_input", 2586408642, .{enable}); }

    pub fn isProcessingUnhandledInput(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing_unhandled_input", 36873697, .{}); }

    pub fn setProcessUnhandledKeyInput(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_unhandled_key_input", 2586408642, .{enable}); }

    pub fn isProcessingUnhandledKeyInput(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing_unhandled_key_input", 36873697, .{}); }

    pub fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_mode", 1841290486, .{mode}); }

    pub fn getProcessMode(self: @This()) !Node.ProcessMode { return support.ptrcallMethod(self, Node.ProcessMode, "Node", "get_process_mode", 739966102, .{}); }

    pub fn canProcess(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "can_process", 36873697, .{}); }

    pub fn setProcessThreadGroup(self: @This(), mode: Node.ProcessThreadGroup) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_thread_group", 2275442745, .{mode}); }

    pub fn getProcessThreadGroup(self: @This()) !Node.ProcessThreadGroup { return support.ptrcallMethod(self, Node.ProcessThreadGroup, "Node", "get_process_thread_group", 1866404740, .{}); }

    pub fn setProcessThreadMessages(self: @This(), flags: Node.ProcessThreadMessages) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_thread_messages", 1357280998, .{flags}); }

    pub fn getProcessThreadMessages(self: @This()) !Node.ProcessThreadMessages { return support.ptrcallMethod(self, Node.ProcessThreadMessages, "Node", "get_process_thread_messages", 4228993612, .{}); }

    pub fn setProcessThreadGroupOrder(self: @This(), order: i64) !void { return support.callVoid(self, "set_process_thread_group_order", .{order}); }

    pub fn getProcessThreadGroupOrder(self: @This()) !i64 { return support.call(self, i64, "get_process_thread_group_order", .{}); }

    pub fn queueAccessibilityUpdate(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "queue_accessibility_update", 3218959716, .{}); }

    pub fn setDisplayFolded(self: @This(), fold: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_display_folded", 2586408642, .{fold}); }

    pub fn isDisplayedFolded(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_displayed_folded", 36873697, .{}); }

    pub fn setProcessInternal(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_process_internal", 2586408642, .{enable}); }

    pub fn isProcessingInternal(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_processing_internal", 36873697, .{}); }

    pub fn setPhysicsProcessInternal(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_physics_process_internal", 2586408642, .{enable}); }

    pub fn isPhysicsProcessingInternal(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_physics_processing_internal", 36873697, .{}); }

    pub fn setPhysicsInterpolationMode(self: @This(), mode: Node.PhysicsInterpolationMode) !void { return support.ptrcallMethodVoid(self, "Node", "set_physics_interpolation_mode", 3202404928, .{mode}); }

    pub fn getPhysicsInterpolationMode(self: @This()) !Node.PhysicsInterpolationMode { return support.ptrcallMethod(self, Node.PhysicsInterpolationMode, "Node", "get_physics_interpolation_mode", 2920385216, .{}); }

    pub fn isPhysicsInterpolated(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_physics_interpolated", 36873697, .{}); }

    pub fn isPhysicsInterpolatedAndEnabled(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_physics_interpolated_and_enabled", 36873697, .{}); }

    pub fn resetPhysicsInterpolation(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "reset_physics_interpolation", 3218959716, .{}); }

    pub fn setAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return support.ptrcallMethodVoid(self, "Node", "set_auto_translate_mode", 776149714, .{mode}); }

    pub fn getAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return support.ptrcallMethod(self, Node.AutoTranslateMode, "Node", "get_auto_translate_mode", 2498906432, .{}); }

    pub fn canAutoTranslate(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "can_auto_translate", 36873697, .{}); }

    pub fn setTranslationDomainInherited(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "set_translation_domain_inherited", 3218959716, .{}); }

    pub fn getWindow(self: @This()) !?Window { return support.call(self, ?Window, "get_window", .{}); }

    pub fn getLastExclusiveWindow(self: @This()) !?Window { return support.call(self, ?Window, "get_last_exclusive_window", .{}); }

    pub fn getTree(self: @This()) !?SceneTree { return support.call(self, ?SceneTree, "get_tree", .{}); }

    pub fn createTween(self: @This()) !Tween { return support.call(self, Tween, "create_tween", .{}); }

    pub fn duplicate(self: @This(), flags: i64) !?Node { return support.call(self, ?Node, "duplicate", .{flags}); }

    pub fn replaceBy(self: @This(), node: Node, keep_groups: bool) !void { return support.callVoid(self, "replace_by", .{ node, keep_groups }); }

    pub fn setSceneInstanceLoadPlaceholder(self: @This(), load_placeholder: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_scene_instance_load_placeholder", 2586408642, .{load_placeholder}); }

    pub fn getSceneInstanceLoadPlaceholder(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "get_scene_instance_load_placeholder", 36873697, .{}); }

    pub fn setEditableInstance(self: @This(), node: Node, is_editable: bool) !void { return support.callVoid(self, "set_editable_instance", .{ node, is_editable }); }

    pub fn isEditableInstance(self: @This(), node: ?Node) !bool { return support.call(self, bool, "is_editable_instance", .{node}); }

    pub fn getViewport(self: @This()) !?Viewport { return support.call(self, ?Viewport, "get_viewport", .{}); }

    pub fn queueFree(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "queue_free", 3218959716, .{}); }

    pub fn requestReady(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "request_ready", 3218959716, .{}); }

    pub fn isNodeReady(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_node_ready", 36873697, .{}); }

    pub fn setMultiplayerAuthority(self: @This(), id: i64, recursive: bool) !void { return support.callVoid(self, "set_multiplayer_authority", .{ id, recursive }); }

    pub fn getMultiplayerAuthority(self: @This()) !i64 { return support.call(self, i64, "get_multiplayer_authority", .{}); }

    pub fn isMultiplayerAuthority(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_multiplayer_authority", 36873697, .{}); }

    pub fn getMultiplayer(self: @This()) !?MultiplayerAPI { return support.call(self, ?MultiplayerAPI, "get_multiplayer", .{}); }

    pub fn setEditorDescription(self: @This(), editor_description: []const u8) !void { return support.callVoid(self, "set_editor_description", .{editor_description}); }

    pub fn setUniqueNameInOwner(self: @This(), enable: bool) !void { return support.ptrcallMethodVoid(self, "Node", "set_unique_name_in_owner", 2586408642, .{enable}); }

    pub fn isUniqueNameInOwner(self: @This()) !bool { return support.ptrcallMethod(self, bool, "Node", "is_unique_name_in_owner", 36873697, .{}); }

    pub fn updateConfigurationWarnings(self: @This()) !void { return support.ptrcallMethodVoid(self, "Node", "update_configuration_warnings", 3218959716, .{}); }

    pub fn notifyDeferredThreadGroup(self: @This(), what: i64) !void { return support.callVoid(self, "notify_deferred_thread_group", .{what}); }

    pub fn notifyThreadSafe(self: @This(), what: i64) !void { return support.callVoid(self, "notify_thread_safe", .{what}); }
};
