// Generated by tools/generate_bindings.zig. Do not edit.
const abi = @import("../../abi.zig");
const support = @import("../../class_support.zig");
const Node = @import("node.zig").Node;
const CanvasItem = @import("canvas_item.zig").CanvasItem;
const Window = @import("window.zig").Window;
const SceneTree = @import("scene_tree.zig").SceneTree;
const Tween = @import("tween.zig").Tween;
const Viewport = @import("viewport.zig").Viewport;
const MultiplayerAPI = @import("multiplayer_api.zig").MultiplayerAPI;
const MultiMesh = @import("multi_mesh.zig").MultiMesh;
const Texture2D = @import("texture_2d.zig").Texture2D;
const CanvasLayer = @import("canvas_layer.zig").CanvasLayer;
const World2D = @import("world_2d.zig").World2D;
const Material = @import("material.zig").Material;
const InputEvent = @import("input_event.zig").InputEvent;

pub const Node2D = extern struct {
    owner: u64,

    pub const godot_class = "Node2D";
    pub const emitSignal = support.emitSignal;

    pub fn asNode(self: @This()) Node { return .{ .owner = self.owner }; }

    pub fn asCanvasItem(self: @This()) CanvasItem { return .{ .owner = self.owner }; }

    pub fn setPosition(self: @This(), position: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "set_position", 743155724, .{position}); }

    pub fn setRotation(self: @This(), radians: f64) !void { return support.callVoid(self, "set_rotation", .{radians}); }

    pub fn setRotationDegrees(self: @This(), degrees: f64) !void { return support.callVoid(self, "set_rotation_degrees", .{degrees}); }

    pub fn setSkew(self: @This(), radians: f64) !void { return support.callVoid(self, "set_skew", .{radians}); }

    pub fn setScale(self: @This(), scale: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "set_scale", 743155724, .{scale}); }

    pub fn getPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "get_position", 3341600327, .{}); }

    pub fn getRotation(self: @This()) !f64 { return support.call(self, f64, "get_rotation", .{}); }

    pub fn getRotationDegrees(self: @This()) !f64 { return support.call(self, f64, "get_rotation_degrees", .{}); }

    pub fn getSkew(self: @This()) !f64 { return support.call(self, f64, "get_skew", .{}); }

    pub fn getScale(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "get_scale", 3341600327, .{}); }

    pub fn rotate(self: @This(), radians: f64) !void { return support.callVoid(self, "rotate", .{radians}); }

    pub fn moveLocalX(self: @This(), delta: f64, scaled: bool) !void { return support.callVoid(self, "move_local_x", .{ delta, scaled }); }

    pub fn moveLocalY(self: @This(), delta: f64, scaled: bool) !void { return support.callVoid(self, "move_local_y", .{ delta, scaled }); }

    pub fn translate(self: @This(), offset: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "translate", 743155724, .{offset}); }

    pub fn globalTranslate(self: @This(), offset: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "global_translate", 743155724, .{offset}); }

    pub fn applyScale(self: @This(), ratio: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "apply_scale", 743155724, .{ratio}); }

    pub fn setGlobalPosition(self: @This(), position: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "set_global_position", 743155724, .{position}); }

    pub fn getGlobalPosition(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "get_global_position", 3341600327, .{}); }

    pub fn setGlobalRotation(self: @This(), radians: f64) !void { return support.callVoid(self, "set_global_rotation", .{radians}); }

    pub fn setGlobalRotationDegrees(self: @This(), degrees: f64) !void { return support.callVoid(self, "set_global_rotation_degrees", .{degrees}); }

    pub fn getGlobalRotation(self: @This()) !f64 { return support.call(self, f64, "get_global_rotation", .{}); }

    pub fn getGlobalRotationDegrees(self: @This()) !f64 { return support.call(self, f64, "get_global_rotation_degrees", .{}); }

    pub fn setGlobalSkew(self: @This(), radians: f64) !void { return support.callVoid(self, "set_global_skew", .{radians}); }

    pub fn getGlobalSkew(self: @This()) !f64 { return support.call(self, f64, "get_global_skew", .{}); }

    pub fn setGlobalScale(self: @This(), scale: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "set_global_scale", 743155724, .{scale}); }

    pub fn getGlobalScale(self: @This()) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "get_global_scale", 3341600327, .{}); }

    pub fn lookAt(self: @This(), point: abi.Vector2(f64)) !void { return support.ptrcallMethodVoid(self, "Node2D", "look_at", 743155724, .{point}); }

    pub fn getAngleTo(self: @This(), point: abi.Vector2(f64)) !f64 { return support.call(self, f64, "get_angle_to", .{point}); }

    pub fn toLocal(self: @This(), global_point: abi.Vector2(f64)) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "to_local", 2656412154, .{global_point}); }

    pub fn toGlobal(self: @This(), local_point: abi.Vector2(f64)) !abi.Vector2(f64) { return support.ptrcallMethod(self, abi.Vector2(f64), "Node2D", "to_global", 2656412154, .{local_point}); }

    pub inline fn addSibling(self: @This(), sibling: Node, force_readable_name: bool) !void { return self.asNode().addSibling(sibling, force_readable_name); }

    pub inline fn setName(self: @This(), name: []const u8) !void { return self.asNode().setName(name); }

    pub inline fn addChild(self: @This(), node: Node, force_readable_name: bool, internal: Node.InternalMode) !void { return self.asNode().addChild(node, force_readable_name, internal); }

    pub inline fn removeChild(self: @This(), node: Node) !void { return self.asNode().removeChild(node); }

    pub inline fn reparent(self: @This(), new_parent: Node, keep_global_transform: bool) !void { return self.asNode().reparent(new_parent, keep_global_transform); }

    pub inline fn getChildCount(self: @This(), include_internal: bool) !i64 { return self.asNode().getChildCount(include_internal); }

    pub inline fn getChild(self: @This(), idx: i64, include_internal: bool) !?Node { return self.asNode().getChild(idx, include_internal); }

    pub inline fn hasNode(self: @This(), path: []const u8) !bool { return self.asNode().hasNode(path); }

    pub inline fn getNode(self: @This(), path: []const u8) !?Node { return self.asNode().getNode(path); }

    pub inline fn getNodeOrNull(self: @This(), path: []const u8) !?Node { return self.asNode().getNodeOrNull(path); }

    pub inline fn getParent(self: @This()) !?Node { return self.asNode().getParent(); }

    pub inline fn findChild(self: @This(), pattern: []const u8, recursive: bool, owned: bool) !?Node { return self.asNode().findChild(pattern, recursive, owned); }

    pub inline fn findParent(self: @This(), pattern: []const u8) !?Node { return self.asNode().findParent(pattern); }

    pub inline fn hasNodeAndResource(self: @This(), path: []const u8) !bool { return self.asNode().hasNodeAndResource(path); }

    pub inline fn isInsideTree(self: @This()) !bool { return self.asNode().isInsideTree(); }

    pub inline fn isPartOfEditedScene(self: @This()) !bool { return self.asNode().isPartOfEditedScene(); }

    pub inline fn isAncestorOf(self: @This(), node: Node) !bool { return self.asNode().isAncestorOf(node); }

    pub inline fn isGreaterThan(self: @This(), node: Node) !bool { return self.asNode().isGreaterThan(node); }

    pub inline fn addToGroup(self: @This(), group: []const u8, persistent: bool) !void { return self.asNode().addToGroup(group, persistent); }

    pub inline fn removeFromGroup(self: @This(), group: []const u8) !void { return self.asNode().removeFromGroup(group); }

    pub inline fn isInGroup(self: @This(), group: []const u8) !bool { return self.asNode().isInGroup(group); }

    pub inline fn moveChild(self: @This(), child_node: Node, to_index: i64) !void { return self.asNode().moveChild(child_node, to_index); }

    pub inline fn setOwner(self: @This(), owner: ?Node) !void { return self.asNode().setOwner(owner); }

    pub inline fn getOwner(self: @This()) !?Node { return self.asNode().getOwner(); }

    pub inline fn getIndex(self: @This(), include_internal: bool) !i64 { return self.asNode().getIndex(include_internal); }

    pub inline fn printTree(self: @This()) !void { return self.asNode().printTree(); }

    pub inline fn printTreePretty(self: @This()) !void { return self.asNode().printTreePretty(); }

    pub inline fn setSceneFilePath(self: @This(), scene_file_path: []const u8) !void { return self.asNode().setSceneFilePath(scene_file_path); }

    pub inline fn propagateNotification(self: @This(), what: i64) !void { return self.asNode().propagateNotification(what); }

    pub inline fn setPhysicsProcess(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcess(enable); }

    pub inline fn getPhysicsProcessDeltaTime(self: @This()) !f64 { return self.asNode().getPhysicsProcessDeltaTime(); }

    pub inline fn isPhysicsProcessing(self: @This()) !bool { return self.asNode().isPhysicsProcessing(); }

    pub inline fn getProcessDeltaTime(self: @This()) !f64 { return self.asNode().getProcessDeltaTime(); }

    pub inline fn setProcess(self: @This(), enable: bool) !void { return self.asNode().setProcess(enable); }

    pub inline fn setProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setProcessPriority(priority); }

    pub inline fn getProcessPriority(self: @This()) !i64 { return self.asNode().getProcessPriority(); }

    pub inline fn setPhysicsProcessPriority(self: @This(), priority: i64) !void { return self.asNode().setPhysicsProcessPriority(priority); }

    pub inline fn getPhysicsProcessPriority(self: @This()) !i64 { return self.asNode().getPhysicsProcessPriority(); }

    pub inline fn isProcessing(self: @This()) !bool { return self.asNode().isProcessing(); }

    pub inline fn setProcessInput(self: @This(), enable: bool) !void { return self.asNode().setProcessInput(enable); }

    pub inline fn isProcessingInput(self: @This()) !bool { return self.asNode().isProcessingInput(); }

    pub inline fn setProcessShortcutInput(self: @This(), enable: bool) !void { return self.asNode().setProcessShortcutInput(enable); }

    pub inline fn isProcessingShortcutInput(self: @This()) !bool { return self.asNode().isProcessingShortcutInput(); }

    pub inline fn setProcessUnhandledInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledInput(enable); }

    pub inline fn isProcessingUnhandledInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledInput(); }

    pub inline fn setProcessUnhandledKeyInput(self: @This(), enable: bool) !void { return self.asNode().setProcessUnhandledKeyInput(enable); }

    pub inline fn isProcessingUnhandledKeyInput(self: @This()) !bool { return self.asNode().isProcessingUnhandledKeyInput(); }

    pub inline fn setProcessMode(self: @This(), mode: Node.ProcessMode) !void { return self.asNode().setProcessMode(mode); }

    pub inline fn getProcessMode(self: @This()) !Node.ProcessMode { return self.asNode().getProcessMode(); }

    pub inline fn canProcess(self: @This()) !bool { return self.asNode().canProcess(); }

    pub inline fn setProcessThreadGroup(self: @This(), mode: Node.ProcessThreadGroup) !void { return self.asNode().setProcessThreadGroup(mode); }

    pub inline fn getProcessThreadGroup(self: @This()) !Node.ProcessThreadGroup { return self.asNode().getProcessThreadGroup(); }

    pub inline fn setProcessThreadMessages(self: @This(), flags: Node.ProcessThreadMessages) !void { return self.asNode().setProcessThreadMessages(flags); }

    pub inline fn getProcessThreadMessages(self: @This()) !Node.ProcessThreadMessages { return self.asNode().getProcessThreadMessages(); }

    pub inline fn setProcessThreadGroupOrder(self: @This(), order: i64) !void { return self.asNode().setProcessThreadGroupOrder(order); }

    pub inline fn getProcessThreadGroupOrder(self: @This()) !i64 { return self.asNode().getProcessThreadGroupOrder(); }

    pub inline fn queueAccessibilityUpdate(self: @This()) !void { return self.asNode().queueAccessibilityUpdate(); }

    pub inline fn setDisplayFolded(self: @This(), fold: bool) !void { return self.asNode().setDisplayFolded(fold); }

    pub inline fn isDisplayedFolded(self: @This()) !bool { return self.asNode().isDisplayedFolded(); }

    pub inline fn setProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setProcessInternal(enable); }

    pub inline fn isProcessingInternal(self: @This()) !bool { return self.asNode().isProcessingInternal(); }

    pub inline fn setPhysicsProcessInternal(self: @This(), enable: bool) !void { return self.asNode().setPhysicsProcessInternal(enable); }

    pub inline fn isPhysicsProcessingInternal(self: @This()) !bool { return self.asNode().isPhysicsProcessingInternal(); }

    pub inline fn setPhysicsInterpolationMode(self: @This(), mode: Node.PhysicsInterpolationMode) !void { return self.asNode().setPhysicsInterpolationMode(mode); }

    pub inline fn getPhysicsInterpolationMode(self: @This()) !Node.PhysicsInterpolationMode { return self.asNode().getPhysicsInterpolationMode(); }

    pub inline fn isPhysicsInterpolated(self: @This()) !bool { return self.asNode().isPhysicsInterpolated(); }

    pub inline fn isPhysicsInterpolatedAndEnabled(self: @This()) !bool { return self.asNode().isPhysicsInterpolatedAndEnabled(); }

    pub inline fn resetPhysicsInterpolation(self: @This()) !void { return self.asNode().resetPhysicsInterpolation(); }

    pub inline fn setAutoTranslateMode(self: @This(), mode: Node.AutoTranslateMode) !void { return self.asNode().setAutoTranslateMode(mode); }

    pub inline fn getAutoTranslateMode(self: @This()) !Node.AutoTranslateMode { return self.asNode().getAutoTranslateMode(); }

    pub inline fn canAutoTranslate(self: @This()) !bool { return self.asNode().canAutoTranslate(); }

    pub inline fn setTranslationDomainInherited(self: @This()) !void { return self.asNode().setTranslationDomainInherited(); }

    pub inline fn getWindow(self: @This()) !?Window { return self.asNode().getWindow(); }

    pub inline fn getLastExclusiveWindow(self: @This()) !?Window { return self.asNode().getLastExclusiveWindow(); }

    pub inline fn getTree(self: @This()) !?SceneTree { return self.asNode().getTree(); }

    pub inline fn createTween(self: @This()) !Tween { return self.asNode().createTween(); }

    pub inline fn duplicate(self: @This(), flags: i64) !?Node { return self.asNode().duplicate(flags); }

    pub inline fn replaceBy(self: @This(), node: Node, keep_groups: bool) !void { return self.asNode().replaceBy(node, keep_groups); }

    pub inline fn setSceneInstanceLoadPlaceholder(self: @This(), load_placeholder: bool) !void { return self.asNode().setSceneInstanceLoadPlaceholder(load_placeholder); }

    pub inline fn getSceneInstanceLoadPlaceholder(self: @This()) !bool { return self.asNode().getSceneInstanceLoadPlaceholder(); }

    pub inline fn setEditableInstance(self: @This(), node: Node, is_editable: bool) !void { return self.asNode().setEditableInstance(node, is_editable); }

    pub inline fn isEditableInstance(self: @This(), node: ?Node) !bool { return self.asNode().isEditableInstance(node); }

    pub inline fn getViewport(self: @This()) !?Viewport { return self.asNode().getViewport(); }

    pub inline fn queueFree(self: @This()) !void { return self.asNode().queueFree(); }

    pub inline fn requestReady(self: @This()) !void { return self.asNode().requestReady(); }

    pub inline fn isNodeReady(self: @This()) !bool { return self.asNode().isNodeReady(); }

    pub inline fn setMultiplayerAuthority(self: @This(), id: i64, recursive: bool) !void { return self.asNode().setMultiplayerAuthority(id, recursive); }

    pub inline fn getMultiplayerAuthority(self: @This()) !i64 { return self.asNode().getMultiplayerAuthority(); }

    pub inline fn isMultiplayerAuthority(self: @This()) !bool { return self.asNode().isMultiplayerAuthority(); }

    pub inline fn getMultiplayer(self: @This()) !?MultiplayerAPI { return self.asNode().getMultiplayer(); }

    pub inline fn setEditorDescription(self: @This(), editor_description: []const u8) !void { return self.asNode().setEditorDescription(editor_description); }

    pub inline fn setUniqueNameInOwner(self: @This(), enable: bool) !void { return self.asNode().setUniqueNameInOwner(enable); }

    pub inline fn isUniqueNameInOwner(self: @This()) !bool { return self.asNode().isUniqueNameInOwner(); }

    pub inline fn updateConfigurationWarnings(self: @This()) !void { return self.asNode().updateConfigurationWarnings(); }

    pub inline fn notifyDeferredThreadGroup(self: @This(), what: i64) !void { return self.asNode().notifyDeferredThreadGroup(what); }

    pub inline fn notifyThreadSafe(self: @This(), what: i64) !void { return self.asNode().notifyThreadSafe(what); }

    pub inline fn setVisible(self: @This(), visible: bool) !void { return self.asCanvasItem().setVisible(visible); }

    pub inline fn isVisible(self: @This()) !bool { return self.asCanvasItem().isVisible(); }

    pub inline fn isVisibleInTree(self: @This()) !bool { return self.asCanvasItem().isVisibleInTree(); }

    pub inline fn show(self: @This()) !void { return self.asCanvasItem().show(); }

    pub inline fn hide(self: @This()) !void { return self.asCanvasItem().hide(); }

    pub inline fn queueRedraw(self: @This()) !void { return self.asCanvasItem().queueRedraw(); }

    pub inline fn moveToFront(self: @This()) !void { return self.asCanvasItem().moveToFront(); }

    pub inline fn setAsTopLevel(self: @This(), enable: bool) !void { return self.asCanvasItem().setAsTopLevel(enable); }

    pub inline fn isSetAsTopLevel(self: @This()) !bool { return self.asCanvasItem().isSetAsTopLevel(); }

    pub inline fn setLightMask(self: @This(), light_mask: i64) !void { return self.asCanvasItem().setLightMask(light_mask); }

    pub inline fn getLightMask(self: @This()) !i64 { return self.asCanvasItem().getLightMask(); }

    pub inline fn setZIndex(self: @This(), z_index: i64) !void { return self.asCanvasItem().setZIndex(z_index); }

    pub inline fn getZIndex(self: @This()) !i64 { return self.asCanvasItem().getZIndex(); }

    pub inline fn setZAsRelative(self: @This(), enable: bool) !void { return self.asCanvasItem().setZAsRelative(enable); }

    pub inline fn isZRelative(self: @This()) !bool { return self.asCanvasItem().isZRelative(); }

    pub inline fn setYSortEnabled(self: @This(), enabled: bool) !void { return self.asCanvasItem().setYSortEnabled(enabled); }

    pub inline fn isYSortEnabled(self: @This()) !bool { return self.asCanvasItem().isYSortEnabled(); }

    pub inline fn setDrawBehindParent(self: @This(), enable: bool) !void { return self.asCanvasItem().setDrawBehindParent(enable); }

    pub inline fn isDrawBehindParentEnabled(self: @This()) !bool { return self.asCanvasItem().isDrawBehindParentEnabled(); }

    pub inline fn drawMultimesh(self: @This(), multimesh: MultiMesh, texture: ?Texture2D) !void { return self.asCanvasItem().drawMultimesh(multimesh, texture); }

    pub inline fn drawSetTransform(self: @This(), position: abi.Vector2(f64), rotation: f64, scale: abi.Vector2(f64)) !void { return self.asCanvasItem().drawSetTransform(position, rotation, scale); }

    pub inline fn drawAnimationSlice(self: @This(), animation_length: f64, slice_begin: f64, slice_end: f64, offset: f64) !void { return self.asCanvasItem().drawAnimationSlice(animation_length, slice_begin, slice_end, offset); }

    pub inline fn drawEndAnimation(self: @This()) !void { return self.asCanvasItem().drawEndAnimation(); }

    pub inline fn getLocalMousePosition(self: @This()) !abi.Vector2(f64) { return self.asCanvasItem().getLocalMousePosition(); }

    pub inline fn getGlobalMousePosition(self: @This()) !abi.Vector2(f64) { return self.asCanvasItem().getGlobalMousePosition(); }

    pub inline fn getCanvasLayerNode(self: @This()) !?CanvasLayer { return self.asCanvasItem().getCanvasLayerNode(); }

    pub inline fn getWorld2D(self: @This()) !?World2D { return self.asCanvasItem().getWorld2D(); }

    pub inline fn setMaterial(self: @This(), material: ?Material) !void { return self.asCanvasItem().setMaterial(material); }

    pub inline fn getMaterial(self: @This()) !?Material { return self.asCanvasItem().getMaterial(); }

    pub inline fn setUseParentMaterial(self: @This(), enable: bool) !void { return self.asCanvasItem().setUseParentMaterial(enable); }

    pub inline fn getUseParentMaterial(self: @This()) !bool { return self.asCanvasItem().getUseParentMaterial(); }

    pub inline fn setNotifyLocalTransform(self: @This(), enable: bool) !void { return self.asCanvasItem().setNotifyLocalTransform(enable); }

    pub inline fn isLocalTransformNotificationEnabled(self: @This()) !bool { return self.asCanvasItem().isLocalTransformNotificationEnabled(); }

    pub inline fn setNotifyTransform(self: @This(), enable: bool) !void { return self.asCanvasItem().setNotifyTransform(enable); }

    pub inline fn isTransformNotificationEnabled(self: @This()) !bool { return self.asCanvasItem().isTransformNotificationEnabled(); }

    pub inline fn forceUpdateTransform(self: @This()) !void { return self.asCanvasItem().forceUpdateTransform(); }

    pub inline fn makeCanvasPositionLocal(self: @This(), viewport_point: abi.Vector2(f64)) !abi.Vector2(f64) { return self.asCanvasItem().makeCanvasPositionLocal(viewport_point); }

    pub inline fn makeInputLocal(self: @This(), event: InputEvent) !InputEvent { return self.asCanvasItem().makeInputLocal(event); }

    pub inline fn setVisibilityLayer(self: @This(), layer: i64) !void { return self.asCanvasItem().setVisibilityLayer(layer); }

    pub inline fn getVisibilityLayer(self: @This()) !i64 { return self.asCanvasItem().getVisibilityLayer(); }

    pub inline fn setVisibilityLayerBit(self: @This(), layer: i64, enabled: bool) !void { return self.asCanvasItem().setVisibilityLayerBit(layer, enabled); }

    pub inline fn getVisibilityLayerBit(self: @This(), layer: i64) !bool { return self.asCanvasItem().getVisibilityLayerBit(layer); }

    pub inline fn setTextureFilter(self: @This(), mode: CanvasItem.TextureFilter) !void { return self.asCanvasItem().setTextureFilter(mode); }

    pub inline fn getTextureFilter(self: @This()) !CanvasItem.TextureFilter { return self.asCanvasItem().getTextureFilter(); }

    pub inline fn setTextureRepeat(self: @This(), mode: CanvasItem.TextureRepeat) !void { return self.asCanvasItem().setTextureRepeat(mode); }

    pub inline fn getTextureRepeat(self: @This()) !CanvasItem.TextureRepeat { return self.asCanvasItem().getTextureRepeat(); }

    pub inline fn setClipChildrenMode(self: @This(), mode: CanvasItem.ClipChildrenMode) !void { return self.asCanvasItem().setClipChildrenMode(mode); }

    pub inline fn getClipChildrenMode(self: @This()) !CanvasItem.ClipChildrenMode { return self.asCanvasItem().getClipChildrenMode(); }

    pub inline fn setOversamplingWithScale(self: @This(), enabled: CanvasItem.OversamplingWithScale) !void { return self.asCanvasItem().setOversamplingWithScale(enabled); }

    pub inline fn getOversamplingWithScale(self: @This()) !CanvasItem.OversamplingWithScale { return self.asCanvasItem().getOversamplingWithScale(); }
};
