// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const Node3DGizmo = extern struct {
    owner: u64,

    pub const godot_class = "Node3DGizmo";
    pub const emitSignal = support.emitSignal;
};
