// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const Texture2D = extern struct {
    owner: u64,

    pub const godot_class = "Texture2D";
    pub const emitSignal = support.emitSignal;
};
