// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const TextServer = extern struct {
    owner: u64,

    pub const godot_class = "TextServer";
    pub const emitSignal = support.emitSignal;

    pub const JustificationFlag = enum(i64) {
        justification_none = 0,
        justification_kashida = 1,
        justification_word_bound = 2,
        justification_trim_edge_spaces = 4,
        justification_after_last_tab = 8,
        justification_constrain_ellipsis = 16,
        justification_skip_last_line = 32,
        justification_skip_last_line_with_visible_chars = 64,
        justification_do_not_skip_single_line = 128,
        _,
    };

    pub const Direction = enum(i64) {
        auto = 0,
        ltr = 1,
        rtl = 2,
        inherited = 3,
    };

    pub const Orientation = enum(i64) {
        horizontal = 0,
        vertical = 1,
    };

    pub const LineBreakFlag = enum(i64) {
        break_none = 0,
        break_mandatory = 1,
        break_word_bound = 2,
        break_grapheme_bound = 4,
        break_adaptive = 8,
        break_trim_edge_spaces = 16,
        break_trim_indent = 32,
        break_trim_start_edge_spaces = 64,
        break_trim_end_edge_spaces = 128,
        _,
    };
};
