// Generated by tools/generate_bindings.zig. Do not edit.
const support = @import("../../class_support.zig");

pub const World3D = extern struct {
    owner: u64,

    pub const godot_class = "World3D";
    pub const emitSignal = support.emitSignal;
};
