// Generated by tools/generate_bindings.zig. Do not edit.

pub const HorizontalAlignment = enum(i64) {
    left = 0,
    center = 1,
    right = 2,
    fill = 3,
};

pub const Side = enum(i64) {
    left = 0,
    top = 1,
    right = 2,
    bottom = 3,
};

pub const EulerOrder = enum(i64) {
    xyz = 0,
    xzy = 1,
    yxz = 2,
    yzx = 3,
    zxy = 4,
    zyx = 5,
};
